### ISSUE TITLE
Building the library on GNU/Linux

### ISSUE THREAD

**Issue by speredenn** [usnistgov/REFPROP-cmake#1]
On a ubuntu 15.10 64 bits machine:

```
sudo apt-get install cmake gfortran
git clone --recursive https://github.com/usnistgov/REFPROP-cmake.git
cd REFPROP-cmake
cp -R <REFPROP fortran folder location> FORTRAN   # fortran folder needs to be uppercase
cd FORTRAN
for i in *.F; do mv -- "$i" "${i/%.F/.FOR}"; done   # fortran files are expected to have a .FOR extension
sed -i -e 's/      dll_export/c     dll_export/' PASS_FTN.FOR   # no DLL export for GNU/Linux
cd ..
mkdir build
cd build
cmake ..
cmake --build .
```

This is a proposal for documentation. This procedure generates the library, that I haven't tested for now.

**Comment by ianhbell** [comment]
Thanks for your suggestions!

Why do you not want to output the symbols from the shared library?  We do some magic with symbol aliasing to make sure that we output exactly the same symbols on linux/OSX as we do on windows.

Do you really need to rename the .F files?  The intention is that with this method we support REFPROP versions >9, which should remove this requirement.  Alternatively, we could add the .F files to the glob in the cmake file, which would include them.  So as long as you have EITHER .FOR files or .F files, it would work.

**Comment by speredenn** [comment]
Hello @ianhbell,

It's not that I not wanted to output the symbols. It's just that those dll_exports were generating errors which were stopping the compilation. In the same spirit, your makefile expect the .FOR files, so I had to rename the .F files, to be able to test your code.

I do agree: better with the DLL_exports included. Better with .F files or .FOR files indifferently. I just can testify that on my Ubuntu computer I had to make those modifications to get the code working ;-).

I could have a deeper look to offer a pull request, but I won't be able to do that very soon. I could have a look in May. I'll keep you tuned if I succeed.

**Comment by ianhbell** [comment]
Can you please email me your version of REFPROP fortran source files that are .F for my testing? You can email me at ian.bell@nist.gov.

My goal is to fix ALL these issues, such that it "just works".

Exporting the same symbols on windows and linux is the biggest improvement from this cmake workflow.  It's key to get that working properly.

**Comment by alexhagen** [comment]
In a related issue, I'm able to build and (ostensibly) generate the `dll`s on OSX with a script:

```bash
# Clean the directory except for this file
find . -type f -not -name 'install.sh' -print0 | xargs -0 rm -r --
rm ../FORTRAN/*
cp /Users/hage581/code/COUPPcode/Tools/REFPROP/FORTRAN/* ../FORTRAN/
# uncomment the DEC$ ATTRIBUTES DLLEXPORT lines
sed -i -e 's/cDEC$ ATTRIBUTES/!DEC$ ATTRIBUTES/' ../FORTRAN/PASS_FTN.for   # no DLL export for GNU/Linux
# comment out the dll_export lines
sed -i -e 's/      dll_export/c     dll_export/' ../FORTRAN/PASS_FTN.for   # no DLL export for GNU/Linux
# Build with my gcc and gfortran
CC=/usr/local/Cellar/gcc/8.2.0/bin/gcc-8 FC=gfortran cmake .. -DCMAKE_BUILD_TYPE=Release
CC=/usr/local/Cellar/gcc/8.2.0/bin/gcc-8 FC=gfortran cmake --build .
CC=/usr/local/Cellar/gcc/8.2.0/bin/gcc-8 FC=gfortran cmake --install .
```

However, I get output saying that some tokens are missing:

```bash
Missing from PASS_CMN_tokens:  ['ABFLSHdll', 'ALLPROPS0dll', 'ALLPROPS1dll', 'ALLPROPS20dll', 'ALLPROPSdll', 'BLCRVdll', 'CRTPNTdll', 'DEFL1dll', 'DERVPVTdll', 'DHFL1dll', 'DQFL2dll', 'DSD1dll', 'DSFL1dll', 'ERRMSGdll', 'FLAGSdll', 'GERG08dll', 'GETENUMdll', 'GETMODdll', 'GETREFDIRdll', 'HEATFRMdll', 'HMXORDERdll', 'HSFL1dll', 'IDCRVdll', 'JICRVdll', 'JTCRVdll', 'LIQSPNDLdll', 'MASSFLUXdll', 'MAXPdll', 'MAXTdll', 'MELTKdll', 'PASSCMNdll', 'PEFL1dll', 'PHI0dll', 'PHIDERVdll', 'PHIHMXdll', 'PHIKdll', 'PHIMIXdll', 'PHIXdll', 'RDXHMXdll', 'REDXdll', 'REFPROP1dll', 'REFPROP2dll', 'REFPROPdll', 'RIEMdll', 'RMIX2dll', 'SATESTdll', 'SATGUESSdll', 'SATGVdll', 'SATSPLNdll', 'SETFLUIDSdll', 'SETMIXTUREdll', 'SETREFDIRdll', 'SPLNROOTdll', 'SPLNVALdll', 'STNdll', 'TEFL1dll', 'THFL1dll', 'TPFL2dll', 'TSATDdll', 'TSATPdll', 'TSFL1dll', 'VAPSPNDLdll', 'VIRBCDdll', 'WMOLIdll']
Missing from REFPROP_lib.h: ['DPDDKdll', 'DPDTKdll', 'ACTVYdll', 'SPNDLdll', 'DOTFILLdll']
```
even though it reports that the target has been built.  These errors break the python wrapping:

```python
import os, numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

def NBP():
    RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
    RP.SETPATHdll(os.environ['RPPREFIX'])
    print(RP.RPVersion())
    MOLAR_BASE_SI = RP.GETENUMdll(0,"MOLAR BASE SI").iEnum

    r = RP.REFPROPdll("PROPANE","PQ","T",MOLAR_BASE_SI, 0,0,101325, 0, [1.0])
    print(r.ierr, r.herr, r.Output[0])

if __name__=='__main__':
    # If the RPPREFIX environment variable is not already set by your installer (e.g., on windows),
    # then uncomment this line and set the absolute path to the location of your install of
    # REFPROP
    os.environ['RPPREFIX'] = r'/Users/hage581/util/REFPROP-cmake/build/'

    # Print the version of REFPROP in use and the NBP
    NBP()
```

gives output

```bash
python3.6 testrp.py
8.01c
Traceback (most recent call last):
  File "testrp.py", line 20, in <module>
    NBP()
  File "testrp.py", line 8, in NBP
    MOLAR_BASE_SI = RP.GETENUMdll(0,"MOLAR BASE SI").iEnum
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ctREFPROP/ctREFPROP.py", line 1523, in GETENUMdll
    if self._GETENUMdll is None: raise ValueError("The function GETENUMdll could not be loaded from the shared library.")
ValueError: The function GETENUMdll could not be loaded from the shared library.
```

Is there anyway to have those tokens generated so that python can access them?  I can open this as a new issue since it's a pretty big extension of speredenn's documentation request.

**Comment by ianhbell** [comment]
What version of REFPROP are you using?  The new build system and wrapper is intended for REFPROP 10, although the wrapper will work fine with REFPROP 9+ if you use the legacy interface.

**Comment by olumighty1** [comment]
Hello @ianhbell, I am having a similar problem using REFPROP 9.1 with Python 
"ValueError: The function GETENUMdll could not be loaded from the shared library"
How do I get the legacy interface?

**Comment by alexhagen** [comment]
I believe I have REFPROP 9.1 as well.

**Comment by olumighty1** [comment]
Thanks, @ianhbell. It is now clear to me. Those functions are meant for REFPROP 10 and not for 9.1.

**Comment by alexhagen** [comment]
@ianhbell and @olumighty1 it sounds like there is some fix, although it's not shown in this comment thread.  Were you able to resolve the problem?

**Comment by ianhbell** [comment]
Well, the issue is that those functions are ONLY available in REFPROP 10, not 9.1.  If you use REFPROP 9.1, you need to use the legacy API:

``` python
import os, numpy as np
from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary

def NBP():
    RP = REFPROPFunctionLibrary(os.environ['RPPREFIX'])
    print(RP.RPVersion())
    RP.SETPATHdll(os.environ['RPPREFIX'])
    r = RP.SETUPdll(1,"PROPANE.FLD","HMX.BNC","DEF")
    assert(r.ierr == 0)
    print(RP.PQFLSHdll(101.325, 0, [1.0], 0))

if __name__=='__main__':
    # Print the version of REFPROP in use and the NBP
    NBP()
```

**Comment by alexhagen** [comment]
Thanks, I’ll test this later this afternoon.

Alex Hagen

**Comment by cforem89** [comment]
I'm having an issue getting the build to work on a Linux machine. The configure ran just fine.

The Linux OS is SUSE Version 11.4

Here are the modules I'm using:
- GNU 4.3.4
- Python 2.7.13
- NumPy 1.12.0b1
- Cmake 3.7.1 

Here's the output from cmake .. -DCMAKE_BUILD_TYPE=Release

-- The C compiler identification is GNU 4.3.4
-- The CXX compiler identification is GNU 4.3.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 4.3.4
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Found PythonInterp: /ots/sw/osstoolkit/15.4/sles11-x86_64/bin/python (found version "2.7.13")
-- DEFSYM_FLAG: --using-defsym
-- linux2
Missing from PASS_CMN_tokens:  []
Missing from REFPROP_lib.h: []

-- Configuring done
-- Generating done
-- Build files have been written to: /home/w/wm324d/refprop/cmake/REFPROP-cmake/build

And here's the message I'm getting when I run cmake --build .

gmake[2]: *** No rule to make target '../FORTRAN/PASS_FTN.FOR', needed by 'REFPROP.h.stamp'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/REFPROP_H.dir/all' failed
gmake[1]: *** [CMakeFiles/REFPROP_H.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
gmake: *** [all] Error 2

**Comment by ianhbell** [comment]
Can you please post your configure as well?  You can obscure paths as needed, but I need to see what it found.  It looks like you didn’t pass a path to your FORTRAN folder? Or did you copy the files into the REFPROP-cmake/FORTRAN folder?

**Comment by cforem89** [comment]
Hey Ian,

I thought I posted the results of the configure? Are you looking for something else?

Yes I put the FORTRAN folder in the root (copied from my Windows REFPROP folder)
[cid:image001.png@01D492D6.5A438CA0]
Cheers

-----------------------------------------------------------------------------
Christopher Foreman
Propulsion Engineer
Boeing Defense, Space and Security
Houston, Texas
(832) 224-7007

**Comment by ianhbell** [comment]
Sorry, yeah I guess I meant the shell command you used to do the configure.  But I see that too.  Did you copy your files into the FORTRAN directory then?  Can you give me an ls of the FORTRAN folder?

**Comment by ianhbell** [comment]
There might have been a bug in the path for the header generation.  Can you pull and try again?

**Comment by cforem89** [comment]
That seemed to work. I was able to generate the librefprop.so file and the REFPROP.h files. In the MATLAB legacy wrapper notes it says to rename the file generated by cmake from libREFPRP64.so to librefprop.so. Is this old information? I just want to double check and make sure it generated the correct file

**Comment by ianhbell** [comment]
Ah, great news!  Yeah, that’s the right approach.

But really, you should transition to the Python wrapper as soon as you are able.  Much more functionality that is not in the legacy wrapper.

**Comment by cforem89** [comment]
I eventually will transition to the Python wrapper but right now the old wrapper runs a lot faster (~20x).

So just to be clear, cmake should generate librefprop.so and REFPROP.h correct? Not libREFPRP64.so and REFPROP.h?

**Comment by ianhbell** [comment]
You’re only making one instance of the REFPROPFunctionLibrary and then passing that around, right? That’s the primary speed problem people tend to have, if they don’t so that.

The name generated by the build depends, but on UNIX, it should always be librefprop.so

**Comment by cforem89** [comment]
Ah okay. Now it's more reasonable:
tic
for i = 1:1000
refpropE('h','t',-100,'p',20,'oxygen');
end
toc
tic
for i = 1:1000
refprop10('h','t',-100,'p',20,'oxygen');
end
toc
Elapsed time is 0.153676 seconds.
Elapsed time is 0.402094 seconds.

**Comment by ianhbell** [comment]
Yeah, that makes more sense, are you calling the REFPROPdll function?  For highest speed, you need to still call the lower-level routines like PTFLSHdll.

P.S. I added matlab code block to your code, looks much nicer IMHO
