### ISSUE TITLE
Error with fortran file names

### ISSUE THREAD

**Issue by raphaeltimbo** [usnistgov/REFPROP-cmake#10]
I am having the following error when trying to build.

```
raphael@raphael:~/REFPROP-cmake/build$ cmake --build .
Scanning dependencies of target refprop
[  3%] Building Fortran object CMakeFiles/refprop.dir/fortran/TRNS_TCX.FOR.o
/home/raphael/REFPROP-cmake/fortran/TRNS_TCX.FOR:70: Error: Can't open included file 'commons.for'
CMakeFiles/refprop.dir/build.make:62: recipe for target 'CMakeFiles/refprop.dir/fortran/TRNS_TCX.FOR.o' failed
make[2]: *** [CMakeFiles/refprop.dir/fortran/TRNS_TCX.FOR.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/refprop.dir/all' failed
make[1]: *** [CMakeFiles/refprop.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

I saw on the general notes:

> Platforms other than windows (and sort of OSX) are CASE-SENSITIVE! The folder fortran is not the same as FORTRAN

I think the issue is in the case sensitive but I could not figured out how to solve this.

Using:
Ubuntu 16.04
python 3.6
GNU Fortran (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by ianhbell** [comment]
This is because of the FORTRAN sources you are using that have a typo in the file names for the includes.  On windows, it doesn’t matter because windows is not case-sensitive, but on linux file name case matters.  That was fixed in 9.1.1, and it is no longer a .FOR file extension either.  I emailed you the sources to REFPROP 9.1.1.

**Comment by raphaeltimbo** [comment]
Thanks for the reply.
I tried again with the sources that you have sent me.
First I got this:

```
[100%] Linking Fortran shared library librefprop.so
Traceback (most recent call last):
  File "/home/raphael/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 142, in <module>
    generate_interface_file(os.path.join(args.FORTRAN_path[0],'PASS_FTN.FOR'), 'REFPROP.pyf')
NameError: name 'os' is not defined
CMakeFiles/refprop.dir/build.make:770: recipe for target 'librefprop.so' failed
make[2]: *** [librefprop.so] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/refprop.dir/all' failed
make[1]: *** [CMakeFiles/refprop.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
I believe that generate_header.py is missing a `import os`. I have inserted that and was able to build.

**Comment by ianhbell** [comment]
That doesn’t make a lot of sense.  Did you update your submodules with

git submodule update --init --recursive -- "externals/REFPROP-headers"

? Your script for building the header seems out of date.

**Comment by raphaeltimbo** [comment]
I tried to clone REFPROP-cmake again and then run git submodule update --init --recursive -- "externals/REFPROP-headers", but nothing happens.
Tried to built and got the error again (`NameError: name 'os' is not defined`).

**Comment by ianhbell** [comment]
Can you try again now?  I hadn’t pushed my update to the REFPROP-headers repo.

**Comment by raphaeltimbo** [comment]
It is working now!
