### ISSUE TITLE
Performance issues when running inside a Docker Container

### ISSUE THREAD

**Issue by bigoper** [usnistgov/REFPROP-cmake#103]
# PERFORMANCE ISSUES
## CONTEXT
- I'm using `Python 3.11` (none python version related issue)
- I'm running a loop of 500 cycles
- The loop calculate `Density` based on `Entropy` and `Pressure`
- On my `Mac M1` the loop ends in 4 seconds, running inside a `Docker Container` (on the same Host `Mac M1`) the loop takes 5 minutes.

## MY SETUP
```sh
Software:

    System Software Overview:

      System Version: macOS 12.4 (21F79)
      Kernel Version: Darwin 21.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 134 days 40 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,2
      Chip: Apple M1 Max
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 32 GB
      System Firmware Version: 7459.121.3
      OS Loader Version: 7459.121.3
```

## MY CODE
```py
def calculate_densities(self, entropy, gas_composition, parsed_inputs):
        densities_si = []
        densities_us = []
        
        for p in self.df['pressure_si']:
            try:
                P = p.to('pascal').magnitude if parsed_inputs['unit_system'] == 'US' else p.magnitude * 1e6
                result = self.RP.REFPROPdll(
                    '', 'SP', 'D', self.MASS_BASE_SI, 2, 1, entropy, P, list(gas_composition.values())
                )

                if result.ierr != 0:
                    density = self.density_to_remove
                else:
                    density = result.Output[0]
                
                if density != self.density_to_remove:
                    density_si = Q_(density, 'kg/m^3')
                    density_us = density_si.to('lb/ft^3')
                else:
                    density_si = Q_(self.density_to_remove, 'kg/m^3')
                    density_us = Q_(self.density_to_remove, 'lb/ft^3')
                
                densities_si.append(density_si)
                densities_us.append(density_us)
                
            except Exception as e:
                densities_si.append(Q_(self.density_to_remove, 'kg/m^3'))
                densities_us.append(Q_(self.density_to_remove, 'lb/ft^3'))                
        
        return densities_si, densities_us
```

## DOCKERFILE
```Dockerfile
# Use Ubuntu base image that matches your target environment
FROM ubuntu:22.04

# Install Python 3.11 and system dependencies
RUN apt-get update && apt-get install -y \
    git \
    cmake \
    python3.11 \
    python3.11-dev \
    python3-pip \
    gfortran \
    libgfortran5 \
    gcc \
    linux-headers-generic \
    && rm -rf /var/lib/apt/lists/*


# In case we need to troubleshoot the container
RUN apt-get update && apt-get install -y \
    zip \
    unzip \
    vim \
    nano \
    && rm -rf /var/lib/apt/lists/*
# Set working directory in container
WORKDIR /engine_services

# Aliases
RUN echo "alias ll='ls -la'" >> ~/.bashrc

COPY requirements.txt .
RUN python3.11 -m pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY . .

# Command to run the application
CMD ["tail", "-f", "/dev/null"]
# CMD ["python3.11", "-m", "dramatiq", "emc2pdfa_queue", "--processes", "5", "--threads", "1"]
```

## MY INPUTS
```py
parsed_inputs: {'analysis_type': 'standard', 'unit_system': 'US', 'backfill_material': 'soil', 'pressure': <Quantity(1500, 'pound_force_per_square_inch')>, 'pressure_points_count': 500, 'temperature': <Quantity(80, 'degree_Fahrenheit')>, 'grade': <Quantity(80, 'kiloforce_pound / inch ** 2')>, 'pipe_outside_diameter': <Quantity(24, 'inch')>, 'pipe_thickness': <Quantity(0.463, 'inch')>, 'elastic_modulus': <Quantity(30000, 'pound_force_per_square_inch')>, 'flow_stress': <Quantity(90, 'kiloforce_pound / inch ** 2')>, 'backfill_coefficient': 39}
gas_composition: {'carbondioxide': 0.97, 'hydrogen': 0.015, 'methane': 0.005, 'nitrogen': 0.01}
entropy: 1302.2361313694278
```

## COMMAND + TIMING (Docker)
- Running this `inside the docker container` (running on my laptop)
- You can see it takes ~5 minutes
```sh
root@f798940e3b63:/engine_services# python3.11 emc2pdfa_performance_test.py
2024-12-12 15:26:08,220 - engine_services.emc2pdfa_service - INFO - run(): calculating densities
2024-12-12 15:30:33,794 - engine_services.emc2pdfa_service - INFO - run(): densities_to_remove: 171, out of 500
```

## COMMAND + TIMING (Host)
- Running this `on my laptop`
- You can see it takes ~4 seconds
```sh
uv run emc2pdfa_performance_test.py
2024-12-12 10:41:17,956 - engine_services.emc2pdfa_service - INFO - run(): 123: calculating densities
2024-12-12 10:41:21,933 - engine_services.emc2pdfa_service - INFO - run(): 123: densities_to_remove: 171, out of 500
```

# QUESTIONS
- Am I missing something here?
- Is it a `REFPROP` thing or a `Docker` thing?
- Could be related to how it was compiled?

Thank you!!

**Comment by ianhbell** [comment]
How did you build the shared library in the docker container? My guess is that it is a debug build?

**Comment by ianhbell** [comment]
I run in docker all the time, no problem with performance I've seen

**Comment by bigoper** [comment]
Hi @ianhbell 
Thank you so much for your prompt response!

## How did you build the shared library in the docker container?
I've followed these [instructions](https://github.com/usnistgov/REFPROP-cmake?tab=readme-ov-file#instructions)

## My guess is that it is a debug build?
How can I verify that?

## ETC
- Will you be able to share your Dockerfile setup? and/or what steps I should take to have run as it should?

Thanks again!

**Comment by ianhbell** [comment]
Can you show your complete Dockerfile?

**Comment by ianhbell** [comment]
You need to build the shared library inside the docker container. Something like this: https://github.com/usnistgov/REFPROP-tests/blob/master/docker/test/Dockerfile

**Comment by bigoper** [comment]
My complete `Dockerfile`

```dockerfile
# Use Ubuntu base image that matches your target environment
FROM ubuntu:22.04

# Install Python 3.11 and system dependencies
RUN apt-get update && apt-get install -y \
    git \
    cmake \
    python3.11 \
    python3.11-dev \
    python3-pip \
    gfortran \
    libgfortran5 \
    gcc \
    linux-headers-generic \
    && rm -rf /var/lib/apt/lists/*


# In case we need to troubleshoot the container
RUN apt-get update && apt-get install -y \
    zip \
    unzip \
    vim \
    nano \
    && rm -rf /var/lib/apt/lists/*
# Set working directory in container
WORKDIR /engine_services

# Aliases
RUN echo "alias ll='ls -la'" >> ~/.bashrc

COPY requirements.txt .
RUN python3.11 -m pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY . .

# Command to run the application
CMD ["tail", "-f", "/dev/null"]
# CMD ["python3.11", "-m", "dramatiq", "emc2pdfa_queue", "--processes", "5", "--threads", "1"]
```

**Comment by bigoper** [comment]
# UPDATE
I'm now testing using the `Dockerfile` test example that you've provided.
I'll provide update ASAP.

**Comment by ianhbell** [comment]
To be clear: shared libraries from an OSX host cannot be used inside the docker container. You MUST build the shared library inside the container

**Comment by ianhbell** [comment]
Are you sure the files are in the right place _inside the container_?

**Comment by ianhbell** [comment]
That's weird behavior because the script is supposed to throw on the first location, and then fall back to the location inside DLLFILES: https://github.com/usnistgov/REFPROP-cmake/blob/master/generate_aliases.py#L22

**Comment by bigoper** [comment]
It's either the late hour on a bust day, or I'm missing something simple.
I'll look at this again in the next few minutes, I'll start with a clean slat.

**Comment by bigoper** [comment]
OK, this is crazy.
- The `RUN cmake .. -DREFPROP_FORTRAN_PATH=/REFPROP/FORTRAN -DCMAKE_BUILD_TYPE=Release -DREFPROP_NO_NUMPY=ON` fails during the `docker build` phase.
- Removing any `cmake` related command from the `Dockerfile`, build is successful. So, I login to the container and ~continue the build phase (running the `cmake` commands that I've excluded from the `docker build`, and NO ERRORS.

Any idea why?

**Comment by bigoper** [comment]
# UPDATES

## PERFORMANCE ISSUE - RESOLVED
### SETUP 1
- Running on a `Mac M1` (arm64 architecture)
- Building a container for `amd64`
- Compiling REFPROP (per the docs)
- Performance: **SLOW!** ![#f03c15](https://placehold.co/15x15/f03c15/f03c15.png).
```sh 
docker buildx build --platform linux/amd64 -t nist-refprop-buildx-amd64:latest -f Dockerfile .
docker run -it nist-refprop-buildx-amd64:latest bash
```
### SETUP 2
- Running on a `Mac M1` (arm64 architecture)
- Building a container for `arm64`
- Compiling REFPROP (per the docs)
- Performance: **FAST!** ![#c5f015](https://placehold.co/15x15/c5f015/c5f015.png)
```sh
docker buildx build --platform linux/arm64/v8 -t nist-refprop-buildx-arm64-v8:latest -f Dockerfile .
docker run -it nist-refprop-buildx-arm64-v8:latest bash
```

## BUILD REFPROP DURING DOCKER BUILD - NOT RESOLVED

**Comment by ianhbell** [comment]
That makes sense that cross-arch runs would be slow. There is an emulation layer that gets triggered and that sort of thing always has a lot of overhead.

I have zero idea why your builds are not working in the normal way. Did you try to use my Dockerfile exactly? I run that on my M2 all the time (like yesterday).
