### ISSUE TITLE
gfortran doesn't compile

### ISSUE THREAD

**Issue by hurbutun** [usnistgov/REFPROP-cmake#11]
Hi,
I am getting the following error message on OSX

> -- The Fortran compiler identification is unknown
> -- Checking whether Fortran compiler has -isysroot
> -- Checking whether Fortran compiler has -isysroot - yes
> -- Checking whether Fortran compiler supports OSX deployment target flag
> -- Checking whether Fortran compiler supports OSX deployment target flag - yes
> -- Check for working Fortran compiler: /usr/local/bin/gfortran
> -- Check for working Fortran compiler: /usr/local/bin/gfortran  -- broken
> CMake Error at /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/CMakeTestFortranCompiler.cmake:54 (message):
>   The Fortran compiler "/usr/local/bin/gfortran" is not able to compile a
>   simple test program.
> 
>   It fails with the following output:
> 
>    Change Dir: /Users/Hur/documents/refpropCmake/build/CMakeFiles/CMakeTmp
> 
>   
> 
>   Run Build Command:"/usr/bin/make" "cmTC_26922/fast"
> 
>   /Applications/Xcode.app/Contents/Developer/usr/bin/make -f
>   CMakeFiles/cmTC_26922.dir/build.make CMakeFiles/cmTC_26922.dir/build
> 
>   Building Fortran object CMakeFiles/cmTC_26922.dir/testFortranCompiler.f.o
> 
>   /usr/local/bin/gfortran -c
>   /Users/Hur/documents/refpropCmake/build/CMakeFiles/CMakeTmp/testFortranCompiler.f
>   -o CMakeFiles/cmTC_26922.dir/testFortranCompiler.f.o
> 
>   FATAL:/opt/local/bin/../libexec/as/x86_64/as: I don't understand 'm' flag!
> 
>   make[1]: *** [CMakeFiles/cmTC_26922.dir/testFortranCompiler.f.o] Error 1
> 
>   make: *** [cmTC_26922/fast] Error 2
> 
>   
> 
>   
> 
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt:3 (enable_language)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/Hur/documents/refpropCmake/build/CMakeFiles/CMakeOutput.log".
> See also "/Users/Hur/documents/refpropCmake/build/CMakeFiles/CMakeError.log".

I have gfortran version 7.1.0 installed with brew (comes with gcc)

Do you know how I can fix it?

**Comment by ianhbell** [comment]
What version of gfortran do you have? I have
```
647ibmac:~ ihb$ gfortran --version
GNU Fortran (Homebrew GCC 6.3.0_1) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

647ibmac:~ ihb$ cmake --version                                                 
cmake version 3.7.1
```
Can you please also run ```brew doctor``` - perhaps you have some unlinked kegs in your cellar

**Comment by ianhbell** [comment]
Can you please show the entire set of steps that you tried from the root of the git clone?  Your log starts a little too late.

**Comment by hurbutun** [comment]
Below you can find the steps and output messages corresponding to each step

> Hur@tsf-444-wpa-6-127:~/documents$ git clone --recursive https://github.com/usnistgov/REFPROP-cmake.git refpropCmake
> Cloning into 'refpropCmake'...
> remote: Counting objects: 107, done.
> remote: Total 107 (delta 0), reused 0 (delta 0), pack-reused 107
> Receiving objects: 100% (107/107), 19.64 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (56/56), done.
> Checking connectivity... done.
> Submodule 'externals/REFPROP-headers' (https://github.com/CoolProp/REFPROP-headers) registered for path 'externals/REFPROP-headers'
> Cloning into 'externals/REFPROP-headers'...
> remote: Counting objects: 206, done.
> remote: Total 206 (delta 0), reused 0 (delta 0), pack-reused 206
> Receiving objects: 100% (206/206), 48.30 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (126/126), done.
> Checking connectivity... done.
> Submodule path 'externals/REFPROP-headers': checked out 'ab6962883060d93a29f9f469e0e70ebd4ca09411'
> Hur@tsf-444-wpa-6-127:~/documents$ cd refpropCmake/
> Hur@tsf-444-wpa-6-127:~/documents/refpropCmake$ mkdir build
> Hur@tsf-444-wpa-6-127:~/documents/refpropCmake$ cd build
> Hur@tsf-444-wpa-6-127:~/documents/refpropCmake/build$ cmake .. -DCMAKE_BUILD_TYPE=Release
> -- The C compiler identification is AppleClang 8.1.0.8020042
> -- The CXX compiler identification is AppleClang 8.1.0.8020042
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- The Fortran compiler identification is unknown
> -- Checking whether Fortran compiler has -isysroot
> -- Checking whether Fortran compiler has -isysroot - yes
> -- Checking whether Fortran compiler supports OSX deployment target flag
> -- Checking whether Fortran compiler supports OSX deployment target flag - yes
> -- Check for working Fortran compiler: /usr/local/bin/gfortran
> -- Check for working Fortran compiler: /usr/local/bin/gfortran  -- broken
> CMake Error at /usr/local/Cellar/cmake/3.6.3/share/cmake/Modules/CMakeTestFortranCompiler.cmake:54 (message):
>   The Fortran compiler "/usr/local/bin/gfortran" is not able to compile a
>   simple test program.
> 
>   It fails with the following output:
> 
>    Change Dir: /Users/Hur/documents/refpropCmake/build/CMakeFiles/CMakeTmp
> 
>   
> 
>   Run Build Command:"/usr/bin/make" "cmTC_63bed/fast"
> 
>   /Applications/Xcode.app/Contents/Developer/usr/bin/make -f
>   CMakeFiles/cmTC_63bed.dir/build.make CMakeFiles/cmTC_63bed.dir/build
> 
>   Building Fortran object CMakeFiles/cmTC_63bed.dir/testFortranCompiler.f.o
> 
>   /usr/local/bin/gfortran -c
>   /Users/Hur/documents/refpropCmake/build/CMakeFiles/CMakeTmp/testFortranCompiler.f
>   -o CMakeFiles/cmTC_63bed.dir/testFortranCompiler.f.o
> 
>   FATAL:/opt/local/bin/../libexec/as/x86_64/as: I don't understand 'm' flag!
> 
>   make[1]: *** [CMakeFiles/cmTC_63bed.dir/testFortranCompiler.f.o] Error 1
> 
>   make: *** [cmTC_63bed/fast] Error 2
> 
>   
> 
>   
> 
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt:3 (enable_language)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/Hur/documents/refpropCmake/build/CMakeFiles/CMakeOutput.log".
> See also "/Users/Hur/documents/refpropCmake/build/CMakeFiles/CMakeError.log".

**Comment by ianhbell** [comment]
I’m trying a build with 7.1.0 as we speak (or rather, building gfortran 7.1.0 as we speak).  It seems maybe you have another gfortran on your computer that it getting picked first?  When you do `which gfortran` what do you get?

**Comment by hurbutun** [comment]
When I do which gfortran I get:
`/usr/local/bin/gfortran`

Which is an alias file. If I right click and go to 'show original' it goes to:
`/usr/local/Cellar/gcc/7.1.0/bin/gfortran-7`

**Comment by ianhbell** [comment]
For me this works flawlessly, aside from some minimal build warnings:
```
647ibmac:REFPROP-cmake ihb$ mkdir build10
647ibmac:REFPROP-cmake ihb$ cd build10
647ibmac:build10 ihb$ cmake .. -DREFPROP_FORTRAN_PATH=/Volumes/647/Public/Eric/REFPROP/FORTRAN
-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 7.1.0
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag - yes
-- Check for working Fortran compiler: /usr/local/bin/gfortran
-- Check for working Fortran compiler: /usr/local/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/local/bin/gfortran supports Fortran 90
-- Checking whether /usr/local/bin/gfortran supports Fortran 90 -- yes
-- DEFSYM_FLAG:
-- darwin
Missing from PASS_CMN_tokens:  ['DOTFILLdll', 'DPDDKdll', 'DPDTKdll', 'PASSCMN']
Missing from REFPROP_lib.h: ['SETNCdll', 'GETMODdll', 'GERG08dll', 'HMXORDERdll', 'RDXHMXdll', 'WMOLIdll', 'CRTPNTdll', 'MAXTdll', 'MAXPdll', 'DERVPVTdll', 'PHIDERVdll', 'DSD1dll', 'RIEMdll', 'VIRBAdll', 'VIRCAdll', 'B12dll', 'CSTARdll', 'HEATdll', 'HEATFRMdll', 'MASSFLUXdll', 'IDCRVdll', 'BLCRVdll', 'JTCRVdll', 'JICRVdll', 'PASSCMNdll', 'LIQSPNDLdll', 'VAPSPNDLdll', 'TPRHOPRdll', 'DEFL1dll', 'PEFL1dll', 'THFL1dll', 'TSFL1dll', 'TEFL1dll', 'HSFL1dll', 'DQFL2dll', 'SATGUESSdll', 'SATTESTdll', 'SATPESTdll', 'PSATKdll', 'DLSATKdll', 'DVSATKdll', 'TSATDdll', 'FLAGSdll', 'ALLPROPSdll', 'ABFLSHdll']

-- Path to libquadmath.a:/usr/local/Cellar/gcc/7.1.0/lib/gcc/7/gcc/x86_64-apple-darwin16.6.0/7.1.0/../../../libquadmath.a
-- Copied libquadmath.a here.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ihb/Code/REFPROP-cmake/build10
647ibmac:build10 ihb$ cmake --build .
Scanning dependencies of target refprop
[  6%] Building Fortran object CMakeFiles/refprop.dir/Volumes/647/Public/Eric/REFPROP/FORTRAN/CORE_ANC.FOR.o
[ 13%] Building Fortran object CMakeFiles/refprop.dir/Volumes/647/Public/Eric/REFPROP/FORTRAN/CORE_CPP.FOR.o
[ 20%] Building Fortran object CMakeFiles/refprop.dir/Volumes/647/Public/Eric/REFPROP/FORTRAN/CORE_FEQ.FOR.o
[ 26%] Building Fortran object CMakeFiles/refprop.dir/Volumes/647/Public/Eric/REFPROP/FORTRAN/CORE_PR.FOR.o
[ 33%] Building Fortran object CMakeFiles/refprop.dir/Volumes/647/Public/Eric/REFPROP/FORTRAN/FLSH_SUB.FOR.o
[ 40%] Building Fortran object CMakeFiles/refprop.dir/Volumes/647/Public/Eric/REFPROP/FORTRAN/MIX_HMX.FOR.o
[ 46%] Building Fortran object CMakeFiles/refprop.dir/Volumes/647/Public/Eric/REFPROP/FORTRAN/PASS_FTN.FOR.o
[ 53%] Building Fortran object CMakeFiles/refprop.dir/Volumes/647/Public/Eric/REFPROP/FORTRAN/PROP_SUB.FOR.o
[ 60%] Building Fortran object CMakeFiles/refprop.dir/Volumes/647/Public/Eric/REFPROP/FORTRAN/SAT_SUB.FOR.o
/Volumes/647/Public/Eric/REFPROP/FORTRAN/SAT_SUB.FOR:2273:3:

  20     if ((T.lt.Tmin*0.999d0 .and. D/Dc.gt.0.5d0) .and. idir.eq.1)EXIT
   1
/Volumes/647/Public/Eric/REFPROP/FORTRAN/SAT_SUB.FOR:2396:72:

         goto 20
                                                                        2
Warning: Legacy Extension: Label at (1) is not in the same block as the GOTO statement at (2)
[ 66%] Building Fortran object CMakeFiles/refprop.dir/Volumes/647/Public/Eric/REFPROP/FORTRAN/SETUP.FOR.o
[ 73%] Building Fortran object CMakeFiles/refprop.dir/Volumes/647/Public/Eric/REFPROP/FORTRAN/TRNSP.FOR.o
[ 80%] Building Fortran object CMakeFiles/refprop.dir/Volumes/647/Public/Eric/REFPROP/FORTRAN/TRNS_TCX.FOR.o
[ 86%] Building Fortran object CMakeFiles/refprop.dir/Volumes/647/Public/Eric/REFPROP/FORTRAN/TRNS_VIS.FOR.o
[ 93%] Building Fortran object CMakeFiles/refprop.dir/Volumes/647/Public/Eric/REFPROP/FORTRAN/UTILITY.FOR.o
/Volumes/647/Public/Eric/REFPROP/FORTRAN/UTILITY.FOR:4753:72:

           pause 'NaN'
                                                                        1
Warning: Deleted feature: PAUSE statement at (1)
/Volumes/647/Public/Eric/REFPROP/FORTRAN/UTILITY.FOR:4776:72:

         pause 'NaN'
                                                                        1
Warning: Deleted feature: PAUSE statement at (1)
[100%] Linking Fortran shared library librefprop.dylib
Writing the .pyf file with numpy.f2py, please be patient...
Deleting REFPROP.pyf
[100%] Built target refprop
```

**Comment by ianhbell** [comment]
Also:
```
647ibmac:build10 ihb$ ls -l `which gfortran`
lrwxr-xr-x  1 ihb  admin  32 Jul 26 10:54 /usr/local/bin/gfortran -> ../Cellar/gcc/7.1.0/bin/gfortran
```
so we are using the same version of gfortran.

What version of OSX do you have?

**Comment by hurbutun** [comment]
I have version 10.12.5

**Comment by ianhbell** [comment]
1) I have 10.12.6 on my machine
2) Are you able to compile a simple hello-world type application with your gfortran?
3) Are there any other gfortran on your computer?

**Comment by hurbutun** [comment]
Yes I can compile simple fortran codes with my gfortran

I have version 6.3.0_1 which was installed by brew as well

**Comment by ianhbell** [comment]
Hmm…  This should all work fine then.  Can you try with a fresh clone?  Not sure why that would change anything, but it can’t hurt.

**Comment by hurbutun** [comment]
It didn't work. I am trying it on another Mac right now. I will post the updates

**Comment by ianhbell** [comment]
Yes, please do and then we can see what is going on.  All the computers I try this on work fine, but I know that doesn’t help you :/

**Comment by hurbutun** [comment]
On the other computer I got this:

> DREFPROP_FORTRAN_PATH=/Users/raluca/Documents/refpropCmake/FORTRAN
> -- DEFSYM_FLAG: 
> -- darwin
> Traceback (most recent call last):
>   File "/Users/raluca/documents/refpropCmake/generate_aliases.py", line 119, in <module>
>     tokens = tokenize(header_path, FORTRAN_path)
>   File "/Users/raluca/documents/refpropCmake/generate_aliases.py", line 21, in tokenize
>     for line in open(os.path.join(path_to_FORTRAN,"PASS_FTN.FOR"), 'r').readlines():
> IOError: [Errno 2] No such file or directory: '/Users/raluca/Documents/refpropCmake/FORTRAN/PASS_FTN.FOR'
> 
> CMake Error at CMakeLists.txt:84 (file):
>   file failed to open for reading (No such file or directory):
> 
>     /Users/raluca/documents/refpropCmake/build/aliases_string.txt
> 
> 
> -- Path to libquadmath.a:/usr/local/Cellar/gcc/7.1.0/lib/gcc/7/gcc/x86_64-apple-darwin16.6.0/7.1.0/../../../libquadmath.a
> -- Copied libquadmath.a here.
> You have called ADD_LIBRARY for library refprop without any source files. This typically indicates a problem with your CMakeLists.txt file
> -- Configuring incomplete, errors occurred!
> See also "/Users/raluca/documents/refpropCmake/build/CMakeFiles/CMakeOutput.log".​

And on mine I tried to uninstall gcc and cmake and install them again, but there is still a problem with gfortran

**Comment by ianhbell** [comment]
This error strikes me as a typo in your path to the fortran folder on the other computer.  Can you do:

ls /Users/raluca/Documents/refpropCmake/FORTRAN/PASS_FTN.FOR

successfully?

**Comment by hurbutun** [comment]
It doesn't work because the extension of PASS_FTN is .F not .FOR

So should I just change the extension of all the files in the fortran library?

It seems like there is a problem as well with the name of Documents folder. In the error message in my previous post it is small case (i.e. documents). Should I, somehow correct that as well?

**Comment by ianhbell** [comment]
If you have .F files, you have a very old version of REFPROP for which you will have to use https://github.com/jowr/librefprop.so instead.

**Comment by hurbutun** [comment]
I have version 9.1

Isn't it the latest version available?

**Comment by ianhbell** [comment]
Nope, you want 9.1.1, but if you have .F files, you have truly ancient REFPROP.  What are the contents of your FORTRAN folder?

**Comment by hurbutun** [comment]
Below is the content of the fortran folder:
`/Documents/refprop/fortran$ ls -a
./          CORE_ANC.F* CORE_ECS.F* CORE_PR.F*  FLSH_SUB.F* MIX_HMX.F*  SAT_SUB.F*  TRNS_ECS.F*
../         CORE_BWR.F* CORE_FEQ.F* CORE_QUI.F* IDEALGAS.F* PASS_FTN.F* SETUP.F*    TRNS_TCX.F*
.gitignore  CORE_CPP.F* CORE_MLT.F* CORE_STN.F* MANUAL.TXT* PROP_SUB.F* SETUP2.F*   TRNS_VIS.F*
CMNS.F*     CORE_DE.F*  CORE_PH0.F* FLASH2.F*   MIX_AGA8.F* REALGAS.F*  TRNSP.F*    UTILITY.F*`

**Comment by ianhbell** [comment]
Please email me at ian.bell .AT. nist.gov and I will send you the FORTRAN code for 9.1.1

**Comment by hurbutun** [comment]
It works with the fortran library you sent me! Thanks a lot!

Now in build folder I have:
`./                   .DS_Store            CMakeFiles/          aliases_string.txt   libquadmath.a
../                  CMakeCache.txt       Makefile             cmake_install.cmake`

An in CMakeFiles:
`./                               CMakeTmp/                        feature_tests.c
../                              Makefile.cmake                   feature_tests.cxx
.DS_Store                        Makefile2                        progress.marks
3.9.0/                           TargetDirectories.txt            refprop.dir/
CMakeDirectoryInformation.cmake  cmake.check_cache
CMakeOutput.log                  feature_tests.bin*`

Which files/folders am I supposed to copy where now?

**Comment by ianhbell** [comment]
Well, now you need to run cmake --build . , once that completes, it depends on what you want to do with REFPROP.  For me, I tend to make a folder

${HOME}/refprop, and put the .dylib and fluids and mixtures directories in it.  Then I tell whatever I am using that it should look there.

**Comment by hurbutun** [comment]
I ideally want to use it with lua or python but I couldn't manage to load the dylib. Do you have a test script to load the library in lua or python?

**Comment by ianhbell** [comment]
As it happens, I just rejuvenated the python wrappers in the last few days: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python

**Comment by hurbutun** [comment]
Many thanks for your help!

**Comment by ianhbell** [comment]
The python wrappers have been massively improved: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python
