### ISSUE TITLE
Inconsistency between methods in generated REFPROP.h and dynamic library

### ISSUE THREAD

**Issue by cyrilpic** [usnistgov/REFPROP-cmake#12]
While compiling REFPROP 10 (Version 9.4.4.03) source files with this repo, I get a few minor inconsistencies between the generated REFPROP.h and the symbols in the dynamic library:

- RPVERSION (in header) : RPVersion in dylib
- ALLPRP200dll (in header) : not correctly exported in dylib (symbol _allprp200dll_ found)
- UNSETAGAdll (in header) : same as previous (symbol _unsetagadll_ found)

This might be related to ALLPRP200dll and UNSETAGAdll not being present in [REFPROP-headers](https://github.com/CoolProp/REFPROP-headers).

**Comment by ianhbell** [comment]
Thanks for noticing these, I’ll update the build scripts to make sure that they are exported properly

**Comment by ianhbell** [comment]
Thank you for reporting this issue.  I believe this should be entirely repaired.  Please confirm, and close this issue if it works for you.

**Comment by cyrilpic** [comment]
👍 issue is solved!
