### ISSUE TITLE
Cannot find f2py module

### ISSUE THREAD

**Issue by sjormiston** [usnistgov/REFPROP-cmake#14]
I was trying to build the refprop library for Fortran on RHEL 6 and it stopped in the generate_header.py
stage with the error message: "No module named numpy.f2py".
 
Here is the transcript of the build session:
[refprop-cmake-error-01.txt](https://github.com/usnistgov/REFPROP-cmake/files/1467306/refprop-cmake-error-01.txt)

**Comment by ianhbell** [comment]
Sounds like you need to install numpy.  Or if you already have numpy installed, what version of numpy do you have installed?

Try this at a shell (windows, but same idea):

C:\Users\ihb>python
Python 2.7.11 |Anaconda custom (64-bit)| (default, Feb 16 2016, 09:58:36) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import numpy
>>> numpy.__version__
'1.11.3'

**Comment by sjormiston** [comment]
Ian:
Thank you for your email. Here is the result of the commands you said to try:

Python 2.6.6 (r266:84292, Aug  9 2016, 06:11:56)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.4.1'

I downloaded the latest numpy but it would not install because it needs v2.7 of python.

I assume this means that I need to ask my system administrator to install the latest versions of
python and numpy. Please advise.

Scott
________________________________________

**Comment by ianhbell** [comment]
Yeah python 2.6 is pretty ancient.  I would advise you install the anaconda package, which you can install in your home directory without root access (I believe).  I would recommend you install python 3.6 version.  See https://www.anaconda.com/download/#linux

[https://www.anaconda.com/wp-content/themes/anaconda/images/anaconda-card.jpg]<https://www.anaconda.com/download/#linux>

Downloads | Anaconda<https://www.anaconda.com/download/#linux>
www.anaconda.com
Download Anaconda Distribution for 1,000+ Python and R data science packages, a package, environment, and dependency manager, and free community support.



________________________________

**Comment by sjormiston** [comment]
Alright. Thank you. I will try again later after those installations.

Scott
________________________________________

**Comment by sjormiston** [comment]
I installed anaconda3 and retried the build from scratch.
This time I have the following error:
Linking Fortran shared library librefprop.so
Writing the .pyf file with numpy.f2py, please be patient...
Traceback (most recent call last):
  File "/home/meng/sormist/test/refprop/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 161, in <module>
    dd = generate_function_dict('REFPROP.pyf')
  File "/home/meng/sormist/test/refprop/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 121, in generate_function_dict
    output = find_subroutine(lines, output['iend']+1)
  File "/home/meng/sormist/test/refprop/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 81, in find_subroutine
    raise ValueError(lines[istart + 1 + offset].strip())
ValueError: real dimension((ncmax)) :: x0
gmake[2]: *** [librefprop.so] Error 1
gmake[1]: *** [CMakeFiles/refprop.dir/all] Error 2
gmake: *** [all] Error 2

Here is the full transcript: 
[refprop-build-error-2017-11-16.txt](https://github.com/usnistgov/REFPROP-cmake/files/1480885/refprop-build-error-2017-11-16.txt)
Here is the contents of REFPROP.pyf:

[REFPROP_pyf.txt](https://github.com/usnistgov/REFPROP-cmake/files/1480886/REFPROP_pyf.txt)

**Comment by ianhbell** [comment]
Hmm I am totally confused.  How did you end up with real in your .pyf?  They should all be double precision.  That is the cause of the problem, but I'm not sure of the solution; plus the ((ncmax)) also looks funky.  Can you please tell me what version of numpy you have? e.g. :


python -c  "import numpy; print(numpy.__version__)"

What version of REFPROP do you have?  How did you get the sources?

________________________________

**Comment by sjormiston** [comment]
Here is my version of python and numpy:
% python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 13 2017, 12:02:49)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.13.3'
>

To get the REFPROP Cmake files, I did
git clone --recursive https://github.com/usnistgov/REFPROP-cmake.git

Can I tell what version I have from the files it put in REFPROP-cmake?

Scott
________________________________________

**Comment by sjormiston** [comment]
Additional information:
I tried the build using Anacond2 (Python 2.7.14, same version of numpy)
and had the same error.
In case it matters, here are our versions of gcc and cmake

% gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-18)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
% cmake --version
cmake version 2.8.12.2

Scott
________________________________________
