### ISSUE TITLE
IndexError when building REFPROP-cmake

### ISSUE THREAD

**Issue by mhannonj** [usnistgov/REFPROP-cmake#15]
I've been attempting to get access to my REFPROP installation from my Linux OS by using the REFPROP-cmake repository.  I went through the instructions you gave got stuck on the command "cmake --build .".  I get the following error:

[100%] Linking Fortran shared library librefprop.so Writing the .pyf file with numpy.f2py, please be patient...
Traceback (most recent call last):
   File
"/home/mhannonj/REFPROP-cmake/externals/REFPROP-headers/generate_header.py",
line 161, in <module>
     dd = generate_function_dict('REFPROP.pyf')
   File
"/home/mhannonj/REFPROP-cmake/externals/REFPROP-headers/generate_header.py",
line 121, in generate_function_dict
     output = find_subroutine(lines, output['iend']+1)
   File
"/home/mhannonj/REFPROP-cmake/externals/REFPROP-headers/generate_header.py",
line 78, in find_subroutine
     L = re.findall(r'dimension\(([0-9]*)\)', intent_dimension)[0]
IndexError: list index out of range
CMakeFiles/refprop.dir/build.make:770: recipe for target 'librefprop.so' 
failed
make[2]: *** [librefprop.so] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/refprop.dir/all' 
failed
make[1]: *** [CMakeFiles/refprop.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

I saw from Issue 10 another user had a similar issue. I have REFPROP version 9.1, so I had some issues with case-sensitivity of FORTRAN source-code file names.  I tried getting around these by renaming all the FORTRAN files so that all capital letters were replaced with lower case.  Just to be on the safe side, I copied the all-caps versions with the no-caps versions into the same 'fortran' directory.  This is overkill I know, but desperate times...

Anyway, this got me beyond the issues with opening *.for files with incorrect names, but I'm still stuck here.  Like you suggested on the thread from the link I provided, I tried running "git submodule update --init --recursive -- "externals/REFPROP-headers", but as expected that made no changes.  Any ideas what's causing the IndexError?  I'll be happy to send you any files you request.

I should also mention that I just updated to the newest version of Ubuntu and that when running the initial "cmake" command, I got this included in the printout:

-- linux2
Missing from PASS_CMN_tokens:  ['DHFL1dll', 'PASSCMN', 'PHI0dll'] Missing from REFPROP_lib.h: ['SETNCdll', 'UNSETAGAdll', 'MAXTdll', 'MAXPdll', 'B12dll', 'VIRBAdll', 'VIRCAdll', 'HEATdll', 'SATTESTdll', 'SATPESTdll', 'PSATKdll', 'DLSATKdll', 'DVSATKdll', 'TSATDdll', 'TPRHOPRdll', 'DQFL2dll', 'CSTARdll', 'LIQSPNDLdll', 'VAPSPNDLdll', 'OMEGAdll', 'ETAK0dll', 'ETAK1dll', 'ETAKRdll', 'ETAKBdll', 'TCXK0dll', 'TCXKBdll', 'TCXKCdll', 'IDCRVdll', 'BLCRVdll', 'JTCRVdll', 'JICRVdll']

-- REFPROP version <= 9.1 identified by presence of include "'commons.for'"; copying locally and fixing include statement
-- Fixing of FORTRAN files complete. Compilation ready.

Thanks!
- Mikey

**Comment by ianhbell** [comment]
Can you please post the complete log you got at the command prompt showing all the commands you ran and the output you received?  Did you modify the sources yourself?  You should not need to because the CMAKE script does that for you - that’s what this comment is all about: “REFPROP version <= 9.1 identified by presence of include "'commons.for'"; copying locally and fixing include statement”

Also, I may have broken the support for 9.1.  Let me double check and I will fix it if so.

**Comment by ianhbell** [comment]
Fixed by bd16e98cb3cf60cad343bafad8b6edd091ea0df8

You'll need to update submodules and it should "just work" . I tested on my side, no problems.

**Comment by mhannonj** [comment]
It looks like this fixed the build process for me, too.  Thanks!  Among other reasons, I'm setting this up to use with MATLAB 2017b (64-bit).  There was another snag when trying to run the 'refpropm.m' function, which I seemed to find an imperfect solution for.  I've posted that here: https://github.com/usnistgov/REFPROP-wrappers/issues/20
