### ISSUE TITLE
REFPROP.h is not generated

### ISSUE THREAD

**Issue by cyrilpic** [usnistgov/REFPROP-cmake#17]
Since commit 574a89867edf121f8819cb63ee5c48c684a02180, `REFPROP.h` is not generated anymore. Commit comments suggests it should only be generated when missing.
Is there something special to do to have it generated?

**Comment by ianhbell** [comment]
Hmm… I guess I fixed one problem but created a new one.  Let me figure out what I did wrong with my “fix”.

**Comment by ianhbell** [comment]
I think I fixed it, can you please update and check?  This seems like a much better solution.

**Comment by cyrilpic** [comment]
👍 seems to work now. Thanks
