### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:PASS_FTN.FOR

### ISSUE THREAD

**Issue by bsn** [usnistgov/REFPROP-cmake#19]
In latest REFPROP betas and v.10 there is one minor issue, when compiling there is an error

```
Traceback (most recent call last):
  File "/root/REFPROP-cmake/generate_aliases.py", line 125, in <module>
    tokens = tokenize(header_path, FORTRAN_path)
  File "/root/REFPROP-cmake/generate_aliases.py", line 21, in tokenize
    for line in open(os.path.join(path_to_FORTRAN,"PASS_FTN.FOR"), 'r').readlines():
FileNotFoundError: [Errno 2] No such file or directory: '/opt/refprop/fortran/PASS_FTN.FOR'
CMake Error at CMakeLists.txt:148 (file):
  file failed to open for reading (No such file or directory):
    /root/REFPROP-cmake/build/aliases_string.txt
```

the thing is - this file is no sitting inside _**/fortran/DLLFILES**_

I think the path in _**aliases_string.txt**_ should be updated to new one for this version.

**Comment by ianhbell** [comment]
Good point! We made this change but I didn't yet update the cmake since I pull from a fortran folder with all the files in the same folder.

**Comment by ianhbell** [comment]
Closed by ad811a9cc207ee8d296b9d1debae419a114b3d08

**Comment by ianhbell** [comment]
Please don't hesitate to re-open if my fix doesn't work for some reason

**Comment by ayoungpe** [comment]
generate_aliases.py failed on the same issue.  I submitted a [pull request](https://github.com/usnistgov/REFPROP-cmake/pull/20) but the process is still failing at the final build step.  Attempting to compile on linux.
