### ISSUE TITLE
Installation problem: couldn't understand kern.osversion

### ISSUE THREAD

**Issue by ericksonla** [usnistgov/REFPROP-cmake#2]
When I try to follow the installation instructions on my machine, I get:
`
cmake ..
  file COPY cannot find "[mydir]/REFPROP-cmake/gfortran: warning:
  couldn’t understand kern.osversion ‘15.5.0
`

My setup is:
OSX 10.11.5
gcc 4.2.1 (OSX core version)
gfortran 4.9.0 (installed from binary)

It appears this is a gcc/gfortran version issue. I am going to try installing a new set of compilers using homebrew.

**Comment by ericksonla** [comment]
Looks like I got it to work. The compliers that I ultimately used were: 
--gcc: Homebrew gcc 4.9.3
--gfortran: Homebrew GNU Fortran 5.3.0 (installs with gcc via homebrew)

**Comment by ianhbell** [comment]
Ok great, I will update the docs to recommend homebrew gfortran on OSX.  I'll close this issue when I make that change.
