### ISSUE TITLE
Error in executing f2py in Linux

### ISSUE THREAD

**Issue by Dhinesht88** [usnistgov/REFPROP-cmake#23]
Hi,
I need to call REFPROP in a Linux machine (red hat-GLNXA64), therefore I tried to compile the FORTRAN files to create the librefprop.so file following the instruction. I failed while running “cmake --build .” command owing to some errors calling f2py function(line 24- generate_header.py) though f2py is installed in the machine. 
The error says “No module named numpy.f2py.__main__;’numpy.f2py’ is a package and cannot be directly executed” 
I am a beginner to Linux OS and therefore I would greatly appreciate any help to build the .so file.
Thank you in advance.

**Comment by ianhbell** [comment]
Hi! 
1) How are you intending to call REFPROP shared library once you build it?
2) Did you read this section of the docs: https://github.com/usnistgov/REFPROP-cmake#general-notes ? The only solution on Red Hat that seems to work is the use of the Anaconda python installation, the standard python packages don't cut it.  I'm not sure why...
3) Can you please post the entire set of shell output from your first two cmake commands?

**Comment by Dhinesht88** [comment]
Hi,
1)	I want to call the shared object file through MATLAB wrapper (refpropm.m). 
2)	I don’t have Anaconda. If Anaconda is only needed to build then I can check with my IT team. I haven’t tried the general notes so far (disabling numpy). If that is the way in Red Hat machines then I will attempt it. 
3)	Please see the attachment.
Thank you.

[Error_REFPROP.txt](https://github.com/usnistgov/REFPROP-cmake/files/2853287/Error_REFPROP.txt)

**Comment by ianhbell** [comment]
1) refpropm.m is deprecated, interface is only via Python for MATLAB from version 10 onwards; refpropm.m still works, but is unsupported.  To get that to work properly, you need your shared library to export the right symbols, but you don't need the C/C++ header.  That's good news for Red Hat users.  Therefore, disabling the numpy things should work fine I believe.

**Comment by Dhinesht88** [comment]
I will run cmake .. -DREFPROP_NO_NUMPY=ON and proceed to build the .so file. 
I need to call this .so file from python (in the near future). will this .so file be supported or I need to rebuild by enabling the numpy?

**Comment by ianhbell** [comment]
Once you have built the SO, then just follow these instructions: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python .  Let me know if you run into any troubles and we'll get you sorted out.

**Comment by Dhinesht88** [comment]
Hi,
I build the .so file after running "cmake .. -DREFPROP_NO_NUMPY=ON". 
But this generated only the librefprop.so file, not the refprop.h header file. I am getting an error in Matlab while running the testRP.m code. 
"Error using loadlibrary
Could not find file REFPROP.h."
Can you please advise on this?
Thank you.

**Comment by ianhbell** [comment]
That makes sense - the only wrapper for MATLAB that we currently support is via Python: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB . I should delete that file entirely.

**Comment by Dhinesht88** [comment]
Hi,
Is that the same procedure for Linux Red Hat environment as well? 
I am bit confused as I don't find how to use the build ".so" file in the procedure.  Does the new procedure requires the .so file?

**Comment by ianhbell** [comment]
Yup, you need to make folder where you put the SO, the MIXTURES and FLUIDS folders, and then point REFPROPFunctionLibrary to that folder.  It should, in theory, just work.
