### ISSUE TITLE
ISSUE WITH REFPROP 10 ON UBUNTU 18.04

### ISSUE THREAD

**Issue by Arafpo** [usnistgov/REFPROP-cmake#24]
Missing from PASS_CMN_tokens:  ['ABFLSHdll', 'ALLPROPS0dll', 'ALLPROPS1dll', 'ALLPROPS20dll', 'ALLPROPSdll', 'CRTPNTdll', 'DEFL1dll', 'DERVPVTdll', 'DHFL1dll', 'DSD1dll', 'ERRMSGdll', 'FLAGSdll', 'GERG08dll', 'GETENUMdll', 'GETMODdll', 'GETREFDIRdll', 'HEATFRMdll', 'HMXORDERdll', 'HSFL1dll', 'MASSFLUXdll', 'MELTKdll', 'PASSCMNdll', 'PEFL1dll', 'PHI0dll', 'PHIDERVdll', 'PHIHMXdll', 'PHIKdll', 'PHIMIXdll', 'RDXHMXdll', 'REFPROP1dll', 'REFPROP2dll', 'REFPROPdll', 'RIEMdll', 'SATESTdll', 'SATGUESSdll', 'SETFLUIDSdll', 'SETMIXTUREdll', 'SETREFDIRdll', 'STNdll', 'TEFL1dll', 'THFL1dll', 'TSATPdll', 'TSFL1dll', 'VIRBCDdll', 'WMOLIdll']
Missing from REFPROP_lib.h: ['DPDDKdll', 'DPDTKdll', 'ACTVYdll', 'DOTFILLdll', 'OMEGAdll', 'ETAK0dll', 'ETAK1dll', 'ETAKRdll', 'ETAKBdll', 'TCXK0dll', 'TCXKBdll', 'TCXKCdll']

-- REFPROP version <= 9.1 identified by presence of include "'commons.for'"; copying locally and fixing include statement

ANY HELP ?

**Comment by ianhbell** [comment]
Can you please provide more information, including:
1) What version of REFPROP you are using and where you have placed your REFPROP files?
2) The shell commands you ran and the complete set of shell output

Without that, it's hard to know where to start. Given the minimal information I can see above, looks like you have REFPROP 9.1

**Comment by Abbashamade** [comment]
i don't know how to see my version of my refprop but it seems 10 
![43](https://user-images.githubusercontent.com/49720542/56310753-e7731b00-614c-11e9-9fa4-62af487dec05.png)
![21](https://user-images.githubusercontent.com/49720542/56310755-e93cde80-614c-11e9-95c5-88906c752a2d.png)
![1](https://user-images.githubusercontent.com/49720542/56310758-ea6e0b80-614c-11e9-9cc2-2dd66ad5eaf1.png)
![1](https://user-images.githubusercontent.com/49720542/56310772-f22db000-614c-11e9-892a-91d376a41387.png)
![21](https://user-images.githubusercontent.com/49720542/56310773-f22db000-614c-11e9-8453-d690081a56a0.png)
![43](https://user-images.githubusercontent.com/49720542/56310774-f22db000-614c-11e9-9706-8999dbf3bff8.png)

**Comment by ianhbell** [comment]
Hard/impossible to tell.  Where did you get your REFPROP FORTRAN files from?  When you purchased REFPROP, it would come with some information.

FYI, REFPROP-cmake just provides the build system, you still need to have purchased REFPROP to be able to use the code and fluid files.

**Comment by Abbashamade** [comment]
yeah i know i have fortran files and fluids codes and all but what should i copy in the folder else than the fortran ?

**Comment by ianhbell** [comment]
How did you acquire those FORTRAN files and FLD files?  Did you install on windows and then copy them to your linux machine?

**Comment by Abbashamade** [comment]
yeah

**Comment by Abbashamade** [comment]
what should i do instead ?

**Comment by ianhbell** [comment]
So I would recommend you open the windows version, in the splash screen it will tell you what version you have. It must be 9.1 according to your error message.  Did you read the docs about specifying an alternative path to the FORTRAN folder?

**Comment by ianhbell** [comment]
Can you tell me the contents of the build/FORTRAN_temp folder?

**Comment by Abbashamade** [comment]
yeah it ' s 9.1 no i just did  what it is in your code 
COMMONS.FOR
COMTRN.FOR
CORE_ANC.FOR
CORE_BWR.FOR
CORE_CPP.FOR
CORE_DE.FOR
CORE_ECS.FOR
CORE_FEQ.FOR
CORE_MLT.FOR
CORE_PH0.FOR
CORE_PR.FOR
CORE_QUI.FOR
CORE_STN.FOR
FLASH2.FOR
FLSH_SUB.FOR
IDEALGAS.FOR
MIX_AGA8.FOR
MIX_HMX.FOR
PASS_FTN.FOR
PROP_SUB.FOR
REALGAS.FOR
SAT_SUB.FOR
SETUP.FOR
SETUP2.FOR
TRNS_ECS.FOR
TRNSP.FOR
TRNS_TCX.FOR
TRNS_VIS.FOR
UTILITY.FOR

**Comment by ianhbell** [comment]
Definitely REFPROP 9.1.  When did you buy REFPROP?

**Comment by Abbashamade** [comment]
one year  ago

**Comment by ianhbell** [comment]
What is the error message you get again?  Can you please try to remove the build folder, and then show me the complete shell output from all commands?

**Comment by Abbashamade** [comment]
Missing from PASS_CMN_tokens:  ['ABFLSHdll', 'ALLPROPS0dll', 'ALLPROPS1dll', 'ALLPROPS20dll', 'ALLPROPSdll', 'CRTPNTdll', 'DEFL1dll', 'DERVPVTdll', 'DHFL1dll', 'DSD1dll', 'ERRMSGdll', 'FLAGSdll', 'GERG08dll', 'GETENUMdll', 'GETMODdll', 'GETREFDIRdll', 'HEATFRMdll', 'HMXORDERdll', 'HSFL1dll', 'MASSFLUXdll', 'MELTKdll', 'PASSCMNdll', 'PEFL1dll', 'PHI0dll', 'PHIDERVdll', 'PHIHMXdll', 'PHIKdll', 'PHIMIXdll', 'RDXHMXdll', 'REFPROP1dll', 'REFPROP2dll', 'REFPROPdll', 'RIEMdll', 'SATESTdll', 'SATGUESSdll', 'SETFLUIDSdll', 'SETMIXTUREdll', 'SETREFDIRdll', 'STNdll', 'TEFL1dll', 'THFL1dll', 'TSATPdll', 'TSFL1dll', 'VIRBCDdll', 'WMOLIdll']
Missing from REFPROP_lib.h: ['DPDDKdll', 'DPDTKdll', 'ACTVYdll', 'DOTFILLdll', 'OMEGAdll', 'ETAK0dll', 'ETAK1dll', 'ETAKRdll', 'ETAKBdll', 'TCXK0dll', 'TCXKBdll', 'TCXKCdll']

-- REFPROP version <= 9.1 identified by presence of include "'commons.for'"; copying locally and fixing include statement
-- Fixing of FORTRAN files complete. Compilation ready.
-- Set REFPROP_FORTRAN_PATH to /home/abbas/REFPROP-cmake/build/FORTRAN_temp
-- Configuring done
-- Generating done
-- Build files have been written to: /home/abbas/REFPROP-cmake/build

**Comment by Arafpo** [comment]
so what should i do ?

**Comment by ianhbell** [comment]
Please provide the complete shell output from a clean build, including commands like ``mkdir build``, etc.

**Comment by Arafpo** [comment]
From desktop terminal : git clone --recursive https://github.com/usnistgov/REFPROP-cmake.git
Cloning into 'REFPROP-cmake'...
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 273 (delta 0), reused 1 (delta 0), pack-reused 271
Receiving objects: 100% (273/273), 53.82 KiB | 568.00 KiB/s, done.
Resolving deltas: 100% (143/143), done.
Submodule 'externals/REFPROP-headers' (https://github.com/CoolProp/REFPROP-headers) registered for path 'externals/REFPROP-headers'
Cloning into '/home/abbas/REFPROP-cmake/externals/REFPROP-headers'...
remote: Enumerating objects: 6, done.        
remote: Counting objects: 100% (6/6), done.        
remote: Compressing objects: 100% (4/4), done.        
remote: Total 343 (delta 2), reused 6 (delta 2), pack-reused 337        
Receiving objects: 100% (343/343), 103.16 KiB | 346.00 KiB/s, done.
Resolving deltas: 100% (213/213), done.
Submodule path 'externals/REFPROP-headers': checked out '8a641882c6a859f46be722aa3c1258e95a27d7a7'

From cmake folder terminal :
:/REFPROP-cmake$ mkdir build
:~/REFPROP-cmake$ cd build
:~/REFPROP-cmake/build$ cmake .. -DCMAKE_BUILD_TYPE=Release
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 7.3.0
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.7") 
-- DEFSYM_FLAG: --using-defsym
-- linux
Missing from PASS_CMN_tokens:  ['ABFLSHdll', 'ALLPROPS0dll', 'ALLPROPS1dll', 'ALLPROPS20dll', 'ALLPROPSdll', 'CRTPNTdll', 'DEFL1dll', 'DERVPVTdll', 'DHFL1dll', 'DSD1dll', 'ERRMSGdll', 'FLAGSdll', 'GERG08dll', 'GETENUMdll', 'GETMODdll', 'GETREFDIRdll', 'HEATFRMdll', 'HMXORDERdll', 'HSFL1dll', 'MASSFLUXdll', 'MELTKdll', 'PASSCMNdll', 'PEFL1dll', 'PHI0dll', 'PHIDERVdll', 'PHIHMXdll', 'PHIKdll', 'PHIMIXdll', 'RDXHMXdll', 'REFPROP1dll', 'REFPROP2dll', 'REFPROPdll', 'RIEMdll', 'SATESTdll', 'SATGUESSdll', 'SETFLUIDSdll', 'SETMIXTUREdll', 'SETREFDIRdll', 'STNdll', 'TEFL1dll', 'THFL1dll', 'TSATPdll', 'TSFL1dll', 'VIRBCDdll', 'WMOLIdll']
Missing from REFPROP_lib.h: ['DPDDKdll', 'DPDTKdll', 'ACTVYdll', 'DOTFILLdll', 'OMEGAdll', 'ETAK0dll', 'ETAK1dll', 'ETAKRdll', 'ETAKBdll', 'TCXK0dll', 'TCXKBdll', 'TCXKCdll']

-- REFPROP version <= 9.1 identified by presence of include "'commons.for'"; copying locally and fixing include statement
-- Fixing of FORTRAN files complete. Compilation ready.
-- Set REFPROP_FORTRAN_PATH to /home/abbas/REFPROP-cmake/build/FORTRAN_temp
-- Configuring done
-- Generating done

**Comment by Arafpo** [comment]
is this want u want ?

**Comment by ianhbell** [comment]
Yes, that's perfect. What's the result of the build command?

**Comment by Arafpo** [comment]
Nothing only this

**Comment by ianhbell** [comment]
The next step is to build:
```
cmake --build .
```

**Comment by Arafpo** [comment]
Scanning dependencies of target refprop
[  3%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/CORE_ANC.FOR.o
[  6%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/CORE_BWR.FOR.o
[ 10%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/CORE_CPP.FOR.o
[ 13%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/CORE_DE.FOR.o
[ 17%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/CORE_ECS.FOR.o
[ 20%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/CORE_FEQ.FOR.o
[ 24%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/CORE_MLT.FOR.o
[ 27%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/CORE_PH0.FOR.o
[ 31%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/CORE_PR.FOR.o
[ 34%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/CORE_QUI.FOR.o
[ 37%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/CORE_STN.FOR.o
[ 41%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/FLASH2.FOR.o
[ 44%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/FLSH_SUB.FOR.o
[ 48%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/IDEALGAS.FOR.o
[ 51%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/MIX_AGA8.FOR.o
[ 55%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/MIX_HMX.FOR.o
[ 58%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/PASS_FTN.FOR.o
[ 62%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/PROP_SUB.FOR.o
[ 65%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/REALGAS.FOR.o
[ 68%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/SAT_SUB.FOR.o
[ 72%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/SETUP.FOR.o
[ 75%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/SETUP2.FOR.o
[ 79%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/TRNSP.FOR.o
[ 82%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/TRNS_ECS.FOR.o
[ 86%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/TRNS_TCX.FOR.o
[ 89%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/TRNS_VIS.FOR.o
[ 93%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN_temp/UTILITY.FOR.o
[ 96%] Linking Fortran shared library librefprop.so
[ 96%] Built target refprop
Scanning dependencies of target REFPROP_H
[100%] About to build the REFPROP.h header file w/ /usr/bin/python3.6;-u;/home/abbas/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/home/abbas/REFPROP-cmake/build/FORTRAN_temp;--python-exe;/usr/bin/python3.6
Writing the .pyf file with numpy.f2py, please be patient...
Traceback (most recent call last):
  File "/home/abbas/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 176, in <module>
    generate_interface_file(os.path.join(args.FORTRAN_path[0],'PASS_FTN.FOR'), 'REFPROP.pyf', python_exe = args.python_exe[0])
  File "/home/abbas/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 24, in generate_interface_file
    raise ValueError('Unable to call f2py successfully: '+str(err))
ValueError: Unable to call f2py successfully: b'Traceback (most recent call last):\n  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "/usr/local/lib/python3.6/dist-packages/numpy/f2py/__main__.py", line 6, in <module>\n    main()\n  File "/usr/local/lib/python3.6/dist-packages/numpy/f2py/f2py2e.py", line 668, in main\n    run_main(sys.argv[1:])\n  File "/usr/local/lib/python3.6/dist-packages/numpy/f2py/f2py2e.py", line 408, in run_main\n    postlist = callcrackfortran(files, options)\n  File "/usr/local/lib/python3.6/dist-packages/numpy/f2py/f2py2e.py", line 329, in callcrackfortran\n    postlist = crackfortran.crackfortran(files)\n  File "/usr/local/lib/python3.6/dist-packages/numpy/f2py/crackfortran.py", line 3251, in crackfortran\n    readfortrancode(files, crackline)\n  File "/usr/local/lib/python3.6/dist-packages/numpy/f2py/crackfortran.py", line 495, in readfortrancode\n    readfortrancode(fn1, dowithline=dowithline, istop=0)\n  File "/usr/local/lib/python3.6/dist-packages/numpy/f2py/crackfortran.py", line 501, in readfortrancode\n    dowithline(finalline)\n  File "/usr/local/lib/python3.6/dist-packages/numpy/f2py/crackfortran.py", line 796, in crackline\n    analyzeline(m, pat[1], line)\n  File "/usr/local/lib/python3.6/dist-packages/numpy/f2py/crackfortran.py", line 1184, in analyzeline\n    for e in markoutercomma(ll).split(\'@,@\'):\n  File "/usr/local/lib/python3.6/dist-packages/numpy/f2py/crackfortran.py", line 833, in markoutercomma\n    assert not f, repr((f, line, l))\nAssertionError: (-1, \'ncmax=20)     !max number of components in mixtur\', \'ncmax=20)     !max number of components in mixtur\')\n'
CMakeFiles/REFPROP_H.dir/build.make:60: recipe for target 'REFPROP.h.stamp' failed
make[2]: *** [REFPROP.h.stamp] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/REFPROP_H.dir/all' failed
make[1]: *** [CMakeFiles/REFPROP_H.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
abbas@abbas:~/REFPROP-cmake/build$

**Comment by Arafpo** [comment]
Help please

**Comment by ianhbell** [comment]
How did you acquire numpy?  Did you install it via anaconda as recommended in the docs?  The build of the shared library did succeed, which is good.

**Comment by Arafpo** [comment]
I did just apt-get numpy

**Comment by Arafpo** [comment]
I INSTALLED THE NUMPY FROM CONDA AND it seems to work for creating library
Scanning dependencies of target REFPROP_H
[100%] About to build the REFPROP.h header file w/ /usr/bin/python;-u;/home/abbas/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/home/abbas/REFPROP-cmake/build/FORTRAN_temp;--python-exe;/usr/bin/python
Writing the .pyf file with numpy.f2py, please be patient...
Deleting REFPROP.pyf
[100%] Built target REFPROP_H

so what is the next step please

**Comment by Arafpo** [comment]
I copied to librefprop.so to /usr/lib but when i was running the examples it isn't defined yet 
it gives me  gfortran EXAMPLE.FOR
/tmp/ccsgC4Ik.o: In function `MAIN__':
EXAMPLE.FOR:(.text+0x1c8): undefined reference to `setup_'
EXAMPLE.FOR:(.text+0x2a1): undefined reference to `info_'
EXAMPLE.FOR:(.text+0x4ea): undefined reference to `critp_'
EXAMPLE.FOR:(.text+0x65a): undefined reference to `satt_'
EXAMPLE.FOR:(.text+0x7db): undefined reference to `satt_'
EXAMPLE.FOR:(.text+0x95c): undefined reference to `satp_'
EXAMPLE.FOR:(.text+0xaed): undefined reference to `tprho_'
EXAMPLE.FOR:(.text+0xc50): undefined reference to `tpflsh_'
EXAMPLE.FOR:(.text+0xdbb): undefined reference to `therm_'
EXAMPLE.FOR:(.text+0xde5): undefined reference to `press_'
EXAMPLE.FOR:(.text+0xe0b): undefined reference to `fgcty_'
EXAMPLE.FOR:(.text+0xe2d): undefined reference to `virb_'
EXAMPLE.FOR:(.text+0xe4f): undefined reference to `virc_'
EXAMPLE.FOR:(.text+0xf46): undefined reference to `dpdd_'
EXAMPLE.FOR:(.text+0xf69): undefined reference to `dpdd2_'
EXAMPLE.FOR:(.text+0xf8f): undefined reference to `dpdt_'
EXAMPLE.FOR:(.text+0x10a1): undefined reference to `dhd1_'
EXAMPLE.FOR:(.text+0x121b): undefined reference to `surft_'
EXAMPLE.FOR:(.text+0x1319): undefined reference to `trnprp_'
EXAMPLE.FOR:(.text+0x147d): undefined reference to `tdflsh_'
EXAMPLE.FOR:(.text+0x15fc): undefined reference to `pdflsh_'
EXAMPLE.FOR:(.text+0x177b): undefined reference to `phflsh_'
EXAMPLE.FOR:(.text+0x18fa): undefined reference to `psflsh_'
EXAMPLE.FOR:(.text+0x1a79): undefined reference to `dhflsh_'
EXAMPLE.FOR:(.text+0x1c0e): undefined reference to `thflsh_'
EXAMPLE.FOR:(.text+0x1d4b): undefined reference to `meltt_'
EXAMPLE.FOR:(.text+0x1e69): undefined reference to `sublt_'
EXAMPLE.FOR:(.text+0x21cc): undefined reference to `setup_'
EXAMPLE.FOR:(.text+0x2336): undefined reference to `tqfl2_'
collect2: error: ld returned 1 exit status

**Comment by ianhbell** [comment]
What shell command did you try to run to build the example? What example are you referring to?

In general, this repo is intended for building REFPROP to a shared library that is late-linked into existing code, but it should work in the manner you indicate.

A way to check what symbols are exported in the .so is to run ``nm librefprop.so`` on the shared library, which can help to debug these kinds of issues.

**Comment by Arafpo** [comment]
i did :
gfortran example. for (c     Example program using routines in REFPROP
c       Units are K, kPa, mol/dm^3, mole fraction, J/mol, J/mol-K, m/s
c       uPa-s, W/m-K, and N/m

C   *** See the file MANUAL.TXT in the FORTRAN directory for more routines ***)


and it gives me this  ~/REFPROP-cmake/build$ gfortran EXAMPLE.FOR
/tmp/ccNZPlPg.o: In function `MAIN__':
EXAMPLE.FOR:(.text+0x1c8): undefined reference to `setup_'
EXAMPLE.FOR:(.text+0x2a1): undefined reference to `info_'
EXAMPLE.FOR:(.text+0x4ea): undefined reference to `critp_'
EXAMPLE.FOR:(.text+0x65a): undefined reference to `satt_'
EXAMPLE.FOR:(.text+0x7db): undefined reference to `satt_'
EXAMPLE.FOR:(.text+0x95c): undefined reference to `satp_'
EXAMPLE.FOR:(.text+0xaed): undefined reference to `tprho_'
EXAMPLE.FOR:(.text+0xc50): undefined reference to `tpflsh_'
EXAMPLE.FOR:(.text+0xdbb): undefined reference to `therm_'
EXAMPLE.FOR:(.text+0xde5): undefined reference to `press_'
EXAMPLE.FOR:(.text+0xe0b): undefined reference to `fgcty_'
EXAMPLE.FOR:(.text+0xe2d): undefined reference to `virb_'
EXAMPLE.FOR:(.text+0xe4f): undefined reference to `virc_'
EXAMPLE.FOR:(.text+0xf46): undefined reference to `dpdd_'
EXAMPLE.FOR:(.text+0xf69): undefined reference to `dpdd2_'
EXAMPLE.FOR:(.text+0xf8f): undefined reference to `dpdt_'
EXAMPLE.FOR:(.text+0x10a1): undefined reference to `dhd1_'
EXAMPLE.FOR:(.text+0x121b): undefined reference to `surft_'
EXAMPLE.FOR:(.text+0x1319): undefined reference to `trnprp_'
EXAMPLE.FOR:(.text+0x147d): undefined reference to `tdflsh_'
EXAMPLE.FOR:(.text+0x15fc): undefined reference to `pdflsh_'
EXAMPLE.FOR:(.text+0x177b): undefined reference to `phflsh_'
EXAMPLE.FOR:(.text+0x18fa): undefined reference to `psflsh_'
EXAMPLE.FOR:(.text+0x1a79): undefined reference to `dhflsh_'
EXAMPLE.FOR:(.text+0x1c0e): undefined reference to `thflsh_'
EXAMPLE.FOR:(.text+0x1d4b): undefined reference to `meltt_'
EXAMPLE.FOR:(.text+0x1e69): undefined reference to `sublt_'
EXAMPLE.FOR:(.text+0x21cc): undefined reference to `setup_'
EXAMPLE.FOR:(.text+0x2336): undefined reference to `tqfl2_'
collect2: error: ld returned 1 exit status

i run nm librefprop.so and give me this : 

:~/REFPROP-cmake/build$ nm librefprop.so
0000000000112240 r a0.70106
00000000001121e0 r a1.70108
0000000000323ca8 b a1.7823
0000000000112180 r a2.70110
0000000000323ca0 b a2.7824
0000000000112120 r a3.70113
000000000004bae0 T abfl1_
0000000000072250 T abfl1dll_
0000000000072250 T ABFL1dll
000000000004a6d0 T abfl1x_
00000000000468a0 T abfl2_
0000000000072290 T abfl2dll_
0000000000072290 T ABFL2dll
00000000000160f0 T abwr_
                 U acos@@GLIBC_2.2.5
0000000000080f10 T actvy_
0000000000071fa0 T actvydll_
0000000000071fa0 T ACTVYdll
00000000000749f0 T ag_
00000000003dad20 B agasv1_
000000000041a1c0 B agasv2_
00000000004b14e0 B agasv3_
0000000000071ec0 T agdll_
0000000000071ec0 T AGdll
0000000000071500 T amh2or_
000000000010b460 r anaga.5262
                 U atan@@GLIBC_2.2.5
000000000055e3f0 B auxflgs_
00000000001114a0 r b0.65463
0000000000081760 T b12_
0000000000071fc0 T b12dll_
0000000000071fc0 T B12dll
0000000000111460 r b1.65465
0000000000111420 r b2.65467
00000000001113e0 r b3.65470
0000000000107680 r bcp0.8785
00000000003221e0 B bdset_
00000000001045c0 r binco.20590
00000000000fe7d0 T blcrv_
0000000000072a10 T blcrvdll_
0000000000072a10 T BLCRVdll
0000000000321f78 B __bss_start
00000000005600b0 B casbwr_
00000000005603b0 B cascpp_
0000000000560a80 B casfeq_
00000000005615e0 B casph0_
00000000000f46c0 T cbrtx_
00000000004f8fe0 B ccas_
00000000003aa320 B ccon_
0000000000107200 r ccp0.8802
0000000000072310 T ccritdll_
0000000000072310 T CCRITdll
0000000000497b20 B cf2hmx_
00000000005600e0 B cfbwr_
000000000036f260 B cfecs_
0000000000560aa0 B cffeq_
0000000000417940 B cfihmx_
00000000004b3500 B cfxcrt_
0000000000505a40 B cfxhmx_
0000000000389c00 B cfxpr_
00000000000807f0 T chempot_
0000000000071f90 T chempotdll_
0000000000071f90 T CHEMPOTdll
00000000000cf550 T chi_
000000000058a040 B chungpk_
00000000005d29e0 B chungpv_
00000000003dc120 B cite_
000000000041a300 B cnam_
00000000004ce260 B cnam60_
0000000000072920 T DSFL1dll
0000000000050c40 T dsfl2_
0000000000050b80 T dsflsh_
0000000000072210 T dsflshdll_
0000000000072210 T DSFLSHdll
0000000000321ca0 d __dso_handle
0000000000071eb0 T gibbsdll_
0000000000071eb0 T GIBBSdll
0000000000108760 r gijs.8745
0000000000321000 d _GLOBAL_OFFSET_TABLE_
                 w __gmon_start__
0000000000113410 r __GNU_EH_FRAME_HDR
00000000000fbfd0 T gold_
00000000005ebc10 B gvcom_
00000000005ebc20 B gvtemp_
0000000000322220 b h.7832
00000000003abb10 B hchar_
0000000000586240 B hcmod_
0000000000107140 r hcp0.8810
0000000000084110 T heat_
0000000000072010 T heatdll_
0000000000072010 T HEATdll
00000000000724a0 T SURFTdll
0000000000045a60 T surten_
00000000000724c0 T surtendll_
00000000000724c0 T SURTENdll
                 U tan@@GLIBC_2.2.5
                 U tanh@@GLIBC_2.2.5
000000000004ea40 T tbflsh_

00000000000f67e0 T xmass_
00000000000723e0 T xmassdll_
00000000000723e0 T XMASSdll
00000000000f6210 T xmole_
00000000000723f0 T xmoledll_
00000000000723f0 T XMOLEdll
0000000000323c00 b y.7847
0000000000321cc0 D zerost_
0000000000427f60 B zred_

I Wonder what is the problem help please

**Comment by ianhbell** [comment]
You didn't link the REFPROP shared library in your compile :) 

Need to do something like (untested):

gfortran example.for -L/usr/lib -lrefprop

And in your example you will also have to call SETPATH to ensure that the fluid files can be found.

**Comment by Arafpo** [comment]
![Screenshot from 2019-04-19 19-06-32](https://user-images.githubusercontent.com/49720542/56434761-4ca64800-62d6-11e9-8b23-18847962e153.png)
I think it works by generating a file.out but each time should i linked it ?
i thinks it works it create a file .out but have u any suggestion with which app to code in fortran or any advice because i love more interactive interface or how usually programmers code in linux fortran 
and thanks in advance

**Comment by ianhbell** [comment]
I think the issue with compilation of REFPROP is resolved.

Unfortunately I cannot provide general FORTRAN help since that is outside the scope of REFPROP support.  But I would say that personally, I don't use FORTRAN, and prefer to use Python.    The Python support for REFPROP is quite good: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python

**Comment by momengif** [comment]
### I have a prolem with 'vporpressure_bis' function, if you could help!

is there a funvtion in REFPROP called _'vporpressure_bis'_?

I'm trying to run this code using matlab and refprop; https://github.com/LLNL/LH2Transfer

the matlab output as belwo:

Done with ODE solver
now extracting data
Unrecognized function or variable 'vaporpressure_bis'.

Error in Data_extraction (line 22)
nominal.pv1(z,:)=vaporpressure_bis(nominal.uv1(z,end), nominal.rhov1(z));

Error in runNominal (line 16)
Data_extraction;

Error in run (line 91)
evalin('caller', strcat(script, ';'));

**Comment by ianhbell** [comment]
@momengif Please open a new issue with your question. I'm going to remove your comment from this thread since it isn't connected.
