### ISSUE TITLE
Question about running REFPROP in Linux

### ISSUE THREAD

**Issue by Nanay001** [usnistgov/REFPROP-cmake#26]
Hello,
I am trying to install the REPROP program in Linux. So far, I was able to run a Docker image of REFPROP using the script provided in the Code tab of this page.

I got stuck in the last Linux prompt below:
```
nanay001@nanay001-Bonobo-WS:~/REFPROP$ sudo docker build -t "refprop:Dockerfile" .
Sending build context to Docker daemon   2.56kB
Step 1/6 : FROM ubuntu:16.04
 ---> 9361ce633ff1
Step 2/6 : RUN apt-get -y -m update &&     apt-get install -y git cmake g++ gfortran python python-numpy python-pip python-six
 ---> Using cache
 ---> 3b955c28b2c4
Step 3/6 : ADD https://api.github.com/repos/usnistgov/REFPROP-cmake/git/refs/heads/master RPcmake-version.json
Downloading     341B
 ---> Using cache
 ---> c7e748da37a1
Step 4/6 : RUN git clone --recursive https://github.com/usnistgov/REFPROP-cmake &&     cd REFPROP-cmake/ &&     mkdir build &&     cd build/
 ---> Using cache
 ---> ac7c71a827ba
Step 5/6 : WORKDIR REFPROP-cmake/build
 ---> Using cache
 ---> b113a9d5dd7e
Step 6/6 : CMD cmake .. -DREFPROP_FORTRAN_PATH=/91/FORTRAN && cmake --build .
 ---> Using cache
 ---> 0e479a101cc0
Successfully built 0e479a101cc0
Successfully tagged refprop:Dockerfile
nanay001@nanay001-Bonobo-WS:~/REFPROP$ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED              SIZE
webdev              Dockerfile          0e479a101cc0        About a minute ago   551MB
refprop             Dockerfile          0e479a101cc0        About a minute ago   551MB
ubuntu              16.04               9361ce633ff1        5 weeks ago          118MB
hello-world         latest              fce289e99eb9        3 months ago         1.84kB
nanay001@nanay001-Bonobo-WS:~/REFPROP$ sudo docker run -i -t refprop:Dockerfile /bin/bash
[sudo] password for nanay001: 
root@f5aa6172945e:/REFPROP-cmake/build# ls -l
total 0
root@f5aa6172945e:/REFPROP-cmake/build# 
......
```
Could you please explain to me what do I do in the last prompt.  Is the REFPROP program installed? If so, how do I access it? I am kind of new with Docker, so I am not sure if I ran Docker correctly.

**Comment by ianhbell** [comment]
I'm not entirely clear why you want to build REFPROP inside a docker container.  This isn't the general recommendation, rather you should build the shared library on your normal machine and then call the shared library.

There are applications where additional sandboxing is needed and the use of docker makes that easy to implement, but they are advanced use cases.

**Comment by Nanay001** [comment]
Thank you.  I am actually trying to run the Docker image called Refprop that was built from the Docker file posted in this thread. The Docker image is shown in Screenshot 1.
[screenshot_1.pdf](https://github.com/usnistgov/REFPROP-cmake/files/3110033/screenshot_1.pdf)

If I want to install the REFPROP share library from this image, what is the correct Docker command? Please adsive.

**Comment by ianhbell** [comment]
*Why* do you want to use docker in this case?  You should get experience with building REFPROP outside of docker and only then switch to docker once you understand how it should work.  Walk before you run :)

**Comment by Nanay001** [comment]
In order for me to obtain REFPROP.f and the associated files, do I need to purchase the program? I was able to obtain REFPROP.f and its associated files almost a year ago, but I did not gone through github. I could not find REFPROP.f on any directory from github. Please advise.

**Comment by ianhbell** [comment]
That's correct - REFPROP is a paid software, but the build system, and the wrappers, are freely available on github.
