### ISSUE TITLE
Unable to call f2py successfully

### ISSUE THREAD

**Issue by alefcastelli** [usnistgov/REFPROP-cmake#27]
I am having this issue after I run `cmake --build .` The following message appears:
```
MacBook-Pro-di-Alessandro:build alessandrocastelli$ cmake --build .
[  3%] About to build the REFPROP.h header file w/ /Users/alessandrocastelli/Applications/anaconda3/bin/python;-u;/Users/alessandrocastelli/Documents/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/Users/alessandrocastelli/Documents/REFPROP-cmake/fortran;--python-exe;/Users/alessandrocastelli/Applications/anaconda3/bin/python
Writing the .pyf file with numpy.f2py, please be patient...
Traceback (most recent call last):
  File "/Users/alessandrocastelli/Documents/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 176, in <module>
    generate_interface_file(os.path.join(args.FORTRAN_path[0],'PASS_FTN.FOR'), 'REFPROP.pyf', python_exe = args.python_exe[0])
  File "/Users/alessandrocastelli/Documents/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 24, in generate_interface_file
    raise ValueError('Unable to call f2py successfully: '+str(err))
ValueError: Unable to call f2py successfully: b'Traceback (most recent call last):\n  File "/Users/alessandrocastelli/Applications/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main\n    "__main__", mod_spec)\n  File "/Users/alessandrocastelli/Applications/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code\n    exec(code, run_globals)\n  File "/Users/alessandrocastelli/Applications/anaconda3/lib/python3.7/site-packages/numpy/f2py/__main__.py", line 6, in <module>\n    main()\n  File "/Users/alessandrocastelli/Applications/anaconda3/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 685, in main\n    run_main(sys.argv[1:])\n  File "/Users/alessandrocastelli/Applications/anaconda3/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 425, in run_main\n    postlist = callcrackfortran(files, options)\n  File "/Users/alessandrocastelli/Applications/anaconda3/lib/python3.7/site-packages/numpy/f2py/f2py2e.py", line 329, in callcrackfortran\n    postlist = crackfortran.crackfortran(files)\n  File "/Users/alessandrocastelli/Applications/anaconda3/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 3251, in crackfortran\n    readfortrancode(files, crackline)\n  File "/Users/alessandrocastelli/Applications/anaconda3/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 495, in readfortrancode\n    readfortrancode(fn1, dowithline=dowithline, istop=0)\n  File "/Users/alessandrocastelli/Applications/anaconda3/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 501, in readfortrancode\n    dowithline(finalline)\n  File "/Users/alessandrocastelli/Applications/anaconda3/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 796, in crackline\n    analyzeline(m, pat[1], line)\n  File "/Users/alessandrocastelli/Applications/anaconda3/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 1184, in analyzeline\n    for e in markoutercomma(ll).split(\'@,@\'):\n  File "/Users/alessandrocastelli/Applications/anaconda3/lib/python3.7/site-packages/numpy/f2py/crackfortran.py", line 833, in markoutercomma\n    assert not f, repr((f, line, l))\nAssertionError: (-1, \'ncmax=20)     !max number of components in mixtur\', \'ncmax=20)     !max number of components in mixtur\')\n'
make[2]: *** [REFPROP.h.stamp] Error 1
make[1]: *** [CMakeFiles/REFPROP_H.dir/all] Error 2
make: *** [all] Error 2
```
I am running on MacOS, python 3.7 installed, numpy version 1.16.2, REFPROP 9.1. I followed all the steps shown on this page, and I can't really understand which is the problem.

I'd be happy if you can help me.

Regards,

Alessandro

**Comment by ianhbell** [comment]
What if you use a python 3.6 environment?  Does that help?  That's what I use personally.

I can't see why it would matter, but who knows.  I wish we didn't need f2py, causes so much troubles.  How are you intending to call the library?

**Comment by alefcastelli** [comment]
I have already tried with a python 3.6 environment, but the exact same error came out. I don't know which may be the problems. Python3 was installed via Anaconda, and I use fortran as Fortran compiler.  Am I forgetting to do something? I want to point out that I am pretty new to Unix systems.

**Comment by ianhbell** [comment]
I wonder if they broke f2py in a newer version of numpy.  Can you roll back to 1.14 or so?

**Comment by ianhbell** [comment]
On windows, everything works fine, I wonder why OSX is "special"

**Comment by alefcastelli** [comment]
Tried with numpy 1.14, still the same error. However, I had a similar problem some days ago with Ubuntu 18.04. Strange, also considering that one of my colleague was able to create the libraries on OSX with no problem.

**Comment by ianhbell** [comment]
Some computers are cursed :)

**Comment by alefcastelli** [comment]
I uninstalled anaconda, and manually installe python 3 and Numpy. Now I get this:

`
[  3%] About to build the REFPROP.h header file w/ /usr/local/bin/python;-u;/Users/alessandrocastelli/Documents/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/Users/alessandrocastelli/Documents/REFPROP-cmake/build/FORTRAN_temp;--python-exe;/usr/local/bin/python
Writing the .pyf file with numpy.f2py, please be patient...
Traceback (most recent call last):
  File "/Users/alessandrocastelli/Documents/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 176, in <module>
    generate_interface_file(os.path.join(args.FORTRAN_path[0],'PASS_FTN.FOR'), 'REFPROP.pyf', python_exe = args.python_exe[0])
  File "/Users/alessandrocastelli/Documents/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 24, in generate_interface_file
    raise ValueError('Unable to call f2py successfully: '+str(err))
ValueError: Unable to call f2py successfully: Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/numpy/f2py/__main__.py", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/numpy/f2py/f2py2e.py", line 685, in main
    run_main(sys.argv[1:])
  File "/usr/local/lib/python2.7/site-packages/numpy/f2py/f2py2e.py", line 425, in run_main
    postlist = callcrackfortran(files, options)
  File "/usr/local/lib/python2.7/site-packages/numpy/f2py/f2py2e.py", line 329, in callcrackfortran
    postlist = crackfortran.crackfortran(files)
  File "/usr/local/lib/python2.7/site-packages/numpy/f2py/crackfortran.py", line 3251, in crackfortran
    readfortrancode(files, crackline)
  File "/usr/local/lib/python2.7/site-packages/numpy/f2py/crackfortran.py", line 495, in readfortrancode
    readfortrancode(fn1, dowithline=dowithline, istop=0)
  File "/usr/local/lib/python2.7/site-packages/numpy/f2py/crackfortran.py", line 501, in readfortrancode
    dowithline(finalline)
  File "/usr/local/lib/python2.7/site-packages/numpy/f2py/crackfortran.py", line 796, in crackline
    analyzeline(m, pat[1], line)
  File "/usr/local/lib/python2.7/site-packages/numpy/f2py/crackfortran.py", line 1184, in analyzeline
    for e in markoutercomma(ll).split('@,@'):
  File "/usr/local/lib/python2.7/site-packages/numpy/f2py/crackfortran.py", line 833, in markoutercomma
    assert not f, repr((f, line, l))
AssertionError: (-1, 'ncmax=20)     !max number of components in mixtur', 'ncmax=20)     !max number of components in mixtur')

make[2]: *** [REFPROP.h.stamp] Error 1
make[1]: *** [CMakeFiles/REFPROP_H.dir/all] Error 2
make: *** [all] Error 2
`

Any idea on why Python 2.7? 

Anyway, thank you for your support.

**Comment by ianhbell** [comment]
How did you "manually" install Python and numpy?

**Comment by ianhbell** [comment]
Have you tried disabling the header generation by adding ``-DREFPROP_NO_NUMPY``?  That might workaround this issue.  If you are going to call from Python, you don't need the .H file.

**Comment by alefcastelli** [comment]
yeah, maybe "manually" is not the right word. Uninstalled Anaconda and installed python3 by downloading it from python.org. Numpy installed with:

`pip3 install numpy`

The only thing that comes to my mind is to try to uninstall gcc, gfortran and python3 and install everything via `brew`.

For completeness I just tell you that:
1. REFPROP-cmake folder created in Documents
2. copied the "fortran" folder from REFPROP installation folder (Windows) and pasted in REFPROP-cmake
3. rename "fortran" into "FORTRAN"
4. Opened terminal in "REFPROP-cmake"
5. `mkdir build`
6. `cd build`
7.  `cmake .. -DCMAKE_BUILD_TYPE=Release` 
8. `cmake --build .` 

I am going to call from Matlab for now (main priority for now).

If you have any suggestion please tell me.

**Comment by ianhbell** [comment]
Try ``cmake .. -DCMAKE_BUILD_TYPE=Release -DREFPROP_NO_NUMPY`` instead.  MATLAB has the same dependency on the shared library...

**Comment by alefcastelli** [comment]
Here what happens:

`MacBook-Pro-di-Alessandro:build alessandrocastelli$ cmake .. -DCMAKE_BUILD_TYPE=Release -DREFPROP_NO_NUMPY
Parse error in command line argument: -DREFPROP_NO_NUMPY
Should be: VAR:type=value
CMake Error: No cmake script provided.
CMake Error: Problem processing arguments. Aborting.`

**Comment by ianhbell** [comment]
Sorry, should be 
cmake .. -DCMAKE_BUILD_TYPE=Release -DREFPROP_NO_NUMPY=ON

**Comment by alefcastelli** [comment]
GREAT! librefprop.dylib was created! Now I try refpropm.m on Matlab and hope everything is fine.

Thank you, really.

**Comment by ianhbell** [comment]
refpropm is deprecated, you should migrate to the new Python interface for MATLAB support: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB

**Comment by ianhbell** [comment]
Glad to hear you got it working.  If you are good, please close the issue

**Comment by alefcastelli** [comment]
Unfortunately there's a pretty big inertia where I work. I'll do my best to convince my colleagues to migrate to the Python interface. However, for now I'll have to use the old refpropm.m, which is giving me this error:
```
>> refpropm('P','T',373.15,'Q',0,'water')
Error using loadlibrary
No supported compiler was found. For options, visit https://www.mathworks.com/support/compilers.

Error in loadlibrary

Error in refpropm (line 235)
    [~,~]=loadlibrary(strcat(BasePath,dllName),strcat(BasePath,REFPROP_header),'alias',libName);
```

any idea?

**Comment by ianhbell** [comment]
Yup, click on the link, install a compiler (ugh….) Or just use the Python interface (download Python+numpy in less than a minute).

**Comment by srgkoshelev** [comment]
I happened to have the same issue. 
Thank you for the workaround, Ian. Do you know whether it is an issue on the numpy side?

**Comment by ianhbell** [comment]
Yes, I suspect so because I have not yet run into this situation on all the builds I have done.
