### ISSUE TITLE
Error building using cygwin

### ISSUE THREAD

**Issue by mbaldwin8** [usnistgov/REFPROP-cmake#28]
Hi I'm trying to use cygwin (gfortran) to compile and build on a windows machine. I've followed the prerequisite steps and the instructions but I'm consistently seeing an error during the `cmake build . ` step

Error output: 
`[ 76%] Building Fortran object CMakeFiles/refprop.dir/fortran/TRNS_VIS.FOR.o`
`[ 82%] Building Fortran object CMakeFiles/refprop.dir/fortran/UTILITY.FOR.o`
`[ 88%] Building Fortran object CMakeFiles/refprop.dir/fortran/DLLFILES/PASS_FTN.FOR.o`
`[ 94%] Linking Fortran shared library cygrefprop.dll'`
`'CMakeFiles/refprop.dir/fortran/DLLFILES/PASS_FTN.FOR.o:PASS_FTN.FOR:(.text+0x0): multiple definition of refpropdll_`
`CMakeFiles/refprop.dir/fortran/PASS_FTN.FOR.o:PASS_FTN.FOR:(.text+0x0): first defined here`
`CMakeFiles/refprop.dir/fortran/DLLFILES/PASS_FTN.FOR.o:PASS_FTN.FOR:(.text+0x4e0): multiple definition of `refprop1dll_`

Any help would be appreciated.

**Comment by ianhbell** [comment]
This is not a configuration that I've used before, but MINGW does work fine.  Might need to add some flags for cygwin builds to the cmake build.  And to mess with the alias generation.  I don't use cygwin, so I'll need some more input from you.  Can you do a verbose build?

**Comment by mbaldwin8** [comment]
I have tried the MINGW method as well and experienced a separate issue.  I will post that here as well in case it is easier problem to diagnose. 

Using the build_dll.bat file I keep getting the following output when it tries to reference the FORTRAN folder:

`CMake Error at CMakeLists.txt:276 (add_library):`
`Syntax error in cmake code when parsing string`
`C:\Program Files (x86)\REFPROP\FORTRAN/CORE_ANC.FOR`
`Invalid escape sequence \P`

Thank you.

**Comment by ianhbell** [comment]
For that one, make sure you use forward slashes.  Cmake doesn't like backslashes in paths.

**Comment by mbaldwin8** [comment]
Exactly, but I provided the path to the FORTRAN folder and Cmake is adding those backslashes,  Is there a work-around to this?

**Comment by ianhbell** [comment]
Can you show what commands you ran?

**Comment by mbaldwin8** [comment]
In the location of the REFPROP-cmake folder, I ran `build_dll.bat 32`

**Comment by ianhbell** [comment]
Huh?  Can I don't know where that batch script came from...

Can you please post the full set of commands you ran at the command prompt along with the shell output?

**Comment by mbaldwin8** [comment]
I decided to ignore the batch file for now and take it step by step.  Everything works fine until I configure the build system.  Here is my command and subsequent output:

`C:\Desktop\REFPROP-cmake\build>cmake .. -DREFPROP_FORTRAN_PATH="C:\Program Files (x86)\REFPROP\FORTRAN" -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release`

Then it detects C compilers and CXX compilers and Fortran compilers successfully, and then comes the CMake parsing error:

`-- Found PythonInterp: C:/AppData/Local/Continuum/miniconda3/python.exe (found version "3.7.3")`
`-- DEFSYM_FLAG: --using-defsym`
`-- Path to libquadmath.a:c:/mingw/bin/../lib/gcc/mingw32/8.2.0/libquadmath.a`
`-- Copied libquadmath.a here.`
`CMake Error at CMakeLists.txt:276 (add_library):`
`  Syntax error in cmake code when parsing string`
`                                                                                                    `
    `C:\Program Files (x86)\REFPROP\FORTRAN/CORE_ANC.FOR`
`                                                                                                    `
  `Invalid escape sequence \P`

There are a total of 14 of these parsing errors all at the same line in CMakeLists.txt

Thank you.

**Comment by ianhbell** [comment]
Right, you need forward slashes in REFPROP_FORTRAN_PATH

**Comment by mbaldwin8** [comment]
Yes, that fixed that part!  Now, for the final command `cmake --build .` I arrive at the exact same error message that I encountered using Cygwin.  I suspect it may have something to do with the gfortran compiler, but I'm not sure.  Here is the output:

`Scanning dependencies of target REFPROP`
`[  5%] Building Fortran object CMakeFiles/REFPROP.dir/C_/Program_Files_(x86)/REFPROP/FORTRAN/CORE_ANC.FOR.obj`
`[ 11%] Building Fortran object CMakeFiles/REFPROP.dir/C_/Program_Files_(x86)/REFPROP/FORTRAN/CORE_FEQ.FOR.obj`
`[ 17%] Building Fortran object CMakeFiles/REFPROP.dir/C_/Program_Files_(x86)/REFPROP/FORTRAN/CORE_PR.FOR.obj`
`[ 23%] Building Fortran object CMakeFiles/REFPROP.dir/C_/Program_Files_(x86)/REFPROP/FORTRAN/FLSH_SUB.FOR.obj`
`[ 29%] Building Fortran object CMakeFiles/REFPROP.dir/C_/Program_Files_(x86)/REFPROP/FORTRAN/MIX_HMX.FOR.obj`
`[ 35%] Building Fortran object CMakeFiles/REFPROP.dir/C_/Program_Files_(x86)/REFPROP/FORTRAN/PASS_FTN.FOR.obj`
`[ 41%] Building Fortran object CMakeFiles/REFPROP.dir/C_/Program_Files_(x86)/REFPROP/FORTRAN/PROP_SUB.FOR.obj`
`[ 47%] Building Fortran object CMakeFiles/REFPROP.dir/C_/Program_Files_(x86)/REFPROP/FORTRAN/REFPROP.FOR.obj`
`[ 52%] Building Fortran object CMakeFiles/REFPROP.dir/C_/Program_Files_(x86)/REFPROP/FORTRAN/SAT_SUB.FOR.obj`
`[ 58%] Building Fortran object CMakeFiles/REFPROP.dir/C_/Program_Files_(x86)/REFPROP/FORTRAN/SETUP.FOR.obj`
`[ 64%] Building Fortran object CMakeFiles/REFPROP.dir/C_/Program_Files_(x86)/REFPROP/FORTRAN/TRNSP.FOR.obj`
`[ 70%] Building Fortran object CMakeFiles/REFPROP.dir/C_/Program_Files_(x86)/REFPROP/FORTRAN/TRNS_TCX.FOR.obj`
`[ 76%] Building Fortran object CMakeFiles/REFPROP.dir/C_/Program_Files_(x86)/REFPROP/FORTRAN/TRNS_VIS.FOR.obj`
`[ 82%] Building Fortran object CMakeFiles/REFPROP.dir/C_/Program_Files_(x86)/REFPROP/FORTRAN/UTILITY.FOR.obj`
`[ 88%] Building Fortran object CMakeFiles/REFPROP.dir/C_/Program_Files_(x86)/REFPROP/FORTRAN/DLLFILES/PASS_FTN.FOR.obj`
`[ 94%] Linking Fortran shared library REFPROP.dll`
`CMakeFiles\REFPROP.dir\build.make:309: recipe for target 'REFPROP.dll' failed`
`CMakeFiles\Makefile2:71: recipe for target 'CMakeFiles/REFPROP.dir/all' failed`
`Makefile:82: recipe for target 'all' failed`
`  `
`CMakeFiles/refprop.dir/fortran/DLLFILES/PASS_FTN.FOR.o:PASS_FTN.FOR:(.text+0x4e0): multiple definition of refprop1dll_`
`CMakeFiles/refprop.dir/fortran/PASS_FTN.FOR.o:PASS_FTN.FOR:(.text+0x0): first defined here`

The above three lines is repeated countless times for differently names REFPROP functions.  Then finally:
`collect2.exe: error: ld returned 1 exit status`
`mingw32-make.exe[2]: *** [REFPROP.dll] Error 1`
`mingw32-make.exe[1]: *** [CMakeFiles/REFPROP.dir/all] Error 2`
`mingw32-make.exe: *** [all] Error 2`

**Comment by ianhbell** [comment]
Have you done anything funky with your REFPROP installation?  Somehow you have PASS_FTN.FOR in both the root FORTRAN folder and the DLLFILES subfolder, recommend you delete one and try a clean build, should fix this issue with multiple definitions.

**Comment by mbaldwin8** [comment]
Yes, that was indeed the problem.  Thank you for the help.
