### ISSUE TITLE
Is it possible to speed up REFPROP use in Fortran?

### ISSUE THREAD

**Issue by sjormiston** [usnistgov/REFPROP-cmake#29]
We have an issue with significantly increased run time when using REFPROP.

We are developing an in-house two-phase CFD code for condensation of binary mixtures using Fortran 95. We are presently switching from our (limited) in-house property routines to REFPROP. Our current problem is that we need to do five REFPROP calls per node in the liquid region and nine REFPROP calls in the gas region. When accounting for the number of nodes and iterations to convergence, we estimate this to be about 3.0e+8 calls over the course of a typical run.  Our run time went from about 20 minutes using our in-house property routines (simple function evaluations) to about 13 hours when using only REFROP for the properties.

We are evaluating transport properties (thermal conductivity, dynamic viscosity), density, and enthalpy for a binary mixture in both the liquid phase and in the gas phase plus the equilibrium condition at the interface.

Is there a way to reduce the run time when using REFPROP like this?

**Comment by ianhbell** [comment]
Hi! Are you working with fixed mixture compositions?  If so, you could use the tabular interpolation of CoolProp+REFPROP.  That would be very fast, likely a microsecond or so per call.  If not, life gets very tricky.

Without knowing more about what kind of models you were using before, I’m not surprised about the speed difference.  REFPROP is much more accurate (and slower) than a lot of other mixture models.  Doing calculations with mixtures in a reliable fashion requires significant computational resources, especially with the complicated pure fluid models we use.

**Comment by sjormiston** [comment]
We are modelling condensation in downflow in a vertical pipe, so the
composition of the mixture in both phases changes along the pipe. We assume axisymmetry so our solution fields (velocity, temperature, mass fraction) vary with radius. Our model is a parabolic Navier-Stokes-based formulation.

We thought about building a table lookup -- is there a tool in Coolprop that builds that for a range of temperature, mass fraction and pressure? Would the calls into REFPROP remain the same but just use a table lookup?

We are also interested to know if it is possible to compute the properties of a non-equilibrium condition -- for example where we know the temperature, concentration (mass fraction), and the pressure. As we understand it, in the standard calls we can specify only two of those three quantities and the third one is assumed to be at equilibrium conditions. In our model, we have all three values at a node -- each from solving its own governing equation.
Thanks.
Scott Ormiston

________________________________________

**Comment by ianhbell** [comment]
Bummer - a change in composition destroys all existing tabular interpolation methods that I am aware of.  CoolProp's tables are for a specified composition, a common case in the refrigerant industry, if not elsewhere. You would then use the low-level interface from CoolProp, with tables generated with REFPROP. But I'm not sure that is a good approach for your problem due to the changing composition.

Not sure I understand the last point.  All calculations with REFPROP assume thermodynamic equilibrium.  For a homogeneous state (gas, liquid), you need three variables to define the state, and T,p,composition is a very common set of state variables.

**Comment by sjormiston** [comment]
Would it be possible to have an interpolation table for a number of discrete composition values
in the range that is expected for the conditions we are modelling? We usually have mass fraction from zero to 0.8 (for example). Could we break that range into values and have a table for each value -- then interpolate between the tables?

My other point is that at a given node in a phase we have the composition from a mass conservation equation solution, the temperature from and energy conservation equation solution, and the pressure from a global mass and momentum constraint. The three values are technically not constrained to be in equilibrium.   In pure steam this would be superheated vapour instead of saturated vapour (although there would be no composition in the set).  Is it possible to have a stable pressure (or temperature) in a mixture that does not correspond to the equilibrium value given by using the other two quantities?

________________________________________

**Comment by ianhbell** [comment]
Indeed, it would be fine to generate a table for each composition, and then interpolate.  I'd consider maybe mass fractions from 0.0 to 0.8 in increments of 0.05 (or so).  If the mixture is "boring", then interpolation should be safe.  If you have a crazier mixture (H2S + methane for instance), all bets are off.

I'm having a hard time wrapping my head around this; two variables are not enough to specify the state for a binary mixture in a homogeneous phase (unless you are saturated, in which case you could iterate to find the right composition given T,P (warning: very slow)).

**Comment by sjormiston** [comment]
We will look into the table generation and interpolation.

As for the state of the mixture, we are still trying to understand the situation. We have three independent values for pressure, temperature, and composition (solutions to model governing equations) but we know that  two of the three can be used to find the third if it is in equilibrium. So, either we have non-equilibrium conditions or we are over-specifying our problem in our governing equations.

We will go work on this issues. I think it will take some time to sort them out.
Thank you kindly for your comments.

Scott
________________________________________

**Comment by ianhbell** [comment]
If by “in equilibrium”, you mean a saturation state, two are enough, if by “in equilibrium” you mean the general case, not so much.  I can make an example to clarify if you can tell be an example binary mixture.

**Comment by sjormiston** [comment]
The mixture is also part of the issue. We have so far been using water-air because that was the mixture
for which we had our in-house property functions and  combination of which we did a lot of modelling in the past.  My graduate student made up his own mixture file to use because of warnings about routines not valid for mixtures with greater than 5%. 

The next mixture we want to use is water-ammonia because there are experiments that we can use for validation. 

That will be followed by refrigerant mixtures, but we are still reviewing the literature on what combinations we will use to compare with previous experiments or modelling.

I will contact the student to get a copy of his mixture file to pass along to you.
Scott

________________________________________

**Comment by ianhbell** [comment]
I see…. water + air is a “bad” mixture, very asymmetric, and linear interpolation would be very questionable in general.  Ammonia+water is somewhat better, but still problematic in REFPROP.

**Comment by sjormiston** [comment]
Here is the modified hmx.bnc file from my student. He also provided some feedback on issues that he had with the information in the lessFAQ document that he was using to help him set up the new entry in the mixture file.

He has been using the new mixture file for steam-air with mass fraction from 0 to 0.8 (for example).

Scott Ormiston

________________________________________

**Comment by ianhbell** [comment]
Umm, I don't see the modified HMX.BNC..  Can you please post just the modified part of it?  When you say "air", are you using the pseudo-pure EOS, or treating air as a mixture of air components?

**Comment by sjormiston** [comment]
I have attached a zip file containing the two files that I was mentioning last email.
I think the lines below are the entries added by my student in HMX_2.BNC.

?Air/Water                                                 [Air (dry)/H2O]
?Kunz and Wagner (2007)
  a7821920/b43a7600            
    KW0      1.             1.             1.             1.             0.             0.             0. 0. 0. 0. 0. 0.
    TC1      0.             0.             0.             0.             0.             0.             0. 0. 0. 0. 0. 0.
    VC1      0.             0.             0.             0.             0.             0.             0. 0. 0. 0. 0. 0.
    TRN      1.d-10         0.             0.             0.             0.             0.             0. 0. 0. 0. 0. 0.
!


I think we are using the pseudo-pure EOS for air, but I am not 100% sure.

________________________________________

**Comment by ianhbell** [comment]
Whoah, I'd be very skeptical of those interaction parameters....  Have you tried to do dewpoint calculations with that model?  I very much doubt that this would yield reasonable values.  A decent check would be against the psychrometric model implemented in CoolProp: http://www.coolprop.org/fluid_properties/HumidAir.html#humid-air

**Comment by sjormiston** [comment]
We are interested only in the saturation temperature and pressure relationship for water
and its pure properties. For the steam-air mixture, we had been doing an ideal mixture calculations for properties and ideal gas behaviour for both air and water. As far as I know, the student compared our old property function results with REFPROP using the HMX_2.BNC and the comparisons were reasonable.

If there is a better way to do this, we are all ears.
________________________________________

**Comment by ianhbell** [comment]
Pure fluid properties in REFPROP for water are VERY accurate.

For humid air, I would start off with the psychrometric approach as implemented in CoolProp (highly accurate pure fluids plus virial expansions to handle the mixture).  Please also see https://scholar.google.com/scholar?oi=bibs&hl=en&cluster=2411728801845017631

**Comment by sjormiston** [comment]
I will look at the paper, thank you.
Just out of curiosity, can CoolProp be called from Fortran 95?

________________________________________

**Comment by ianhbell** [comment]
Yup: http://www.coolprop.org/coolprop/wrappers/FORTRAN/index.html#fortran

**Comment by ianhbell** [comment]
If you can switch to C++, the REFPROP-manager allow for nearly-linear speedup if you have multiple cores to use: https://github.com/usnistgov/REFPROP-manager

**Comment by sjormiston** [comment]
Thank you for the suggestion, but the in-house CFD code is a substantial amount of Fortran 95
that we do not want to re-code. I guess we would need a C++ mainline and call our Fortran routines from it, but I think we would also need to call property routines from within the Fortran. Would they be C++ routines that would be called?
Because the graduate student does not know C++, it would be a substantial delay to his Ph.D. programme to undertake that integration of languages at this stage.

________________________________________

**Comment by ianhbell** [comment]
You could in theory also use “threading” within your FORTRAN code with OpenMP, but I don’t have experience with that, and REFPROP is only partially thread-safe at the FORTRAN level.  A conversion from FORTRAN to C++, while painful in the short run, would be a good investment for the future.
