### ISSUE TITLE
How do I point CoolProp to this REFPROP installation?

### ISSUE THREAD

**Issue by ericksonla** [usnistgov/REFPROP-cmake#3]
It looks like the build process creates a libREFPRP64.dylib. Presumably I need to point CoolProp (via Python wrapper) to this lib somehow. How do I do this?

**Comment by ericksonla** [comment]
Looks like on OSX, the library needs to be moved to /usr/local/lib and renamed librefprop.dylib. I'm not sure how globally appropriate this solution is.

**Comment by ianhbell** [comment]
Yes, that should be the solution on OSX.  I'll update the readme.
