### ISSUE TITLE
Unable to build Refprop-cmake on ubuntu 

### ISSUE THREAD

**Issue by prat777** [usnistgov/REFPROP-cmake#35]
Hello CoolProp Team,

I'm trying to run REFPROP 10.0.0.2 on my ubuntu 18.04 LTS server but I have been generally unsuccessful. I did a wine install for NIST2310.EXE which worked and followed all the instructions in:
https://github.com/usnistgov/REFPROP-cmake.

Instead of copying the Fortran path from .wine, I referenced it with some additional options:

`cmake .. -DREFPROP_FORTRAN_PATH=/home/bob/.wine/drive_c/Program\ \Files\ \(x86\)/REFPROP/FORTRAN -DCMAKE_BUILD_TYPE=Release -DREFPROP_NO_NUMPY=OFF -DREFPROP_NO_PYTHON=OFF`

Then I built it using make and the following error is generated:

```
bob@pepsi:~/REFPROP-cmake/build$ cmake .. -DREFPROP_FORTRAN_PATH=/home/bob/.wine/drive_c/Program\ \Files\ \(x86\)/REFPROP/FORTRAN -DCMAKE_BUILD_TYPE=Release -DREFPROP_NO_NUMPY=OFF -DREFPROP_NO_PYTHON=OFF
-- DEFSYM_FLAG: --using-defsym
-- linux2
Missing from PASS_CMN_tokens:  []
Missing from REFPROP_lib.h: []

-- Configuring done
-- Generating done
-- Build files have been written to: /home/bob/REFPROP-cmake/build
bob@pepsi:~/REFPROP-cmake/build$ make
[ 93%] Built target refprop
[100%] About to build the REFPROP.h header file w/ /usr/bin/python;-u;/home/bob/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/home/bob/.wine/drive_c/Program Files (x86)/REFPROP/FORTRAN/DLLFILES;--python-exe;/usr/bin/python
/bin/sh: 1: Syntax error: "(" unexpected
CMakeFiles/REFPROP_H.dir/build.make:60: recipe for target 'REFPROP.h.stamp' failed
make[2]: *** [REFPROP.h.stamp] Error 2
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/REFPROP_H.dir/all' failed
make[1]: *** [CMakeFiles/REFPROP_H.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
bob@pepsi:~/REFPROP-cmake/build$

```

**Comment by ianhbell** [comment]
This seems like a shell-escaping problem with setting the path to the fortran folder of REFPROP.  I'd recommend you copy the FORTRAN folder to somewhere without spaces in it.  Should work a treat - I do this all the time.

**Comment by prat777** [comment]
Thanks for the help if works great when I just moved it from a directory with no spaces.

**Comment by ianhbell** [comment]
I think it would also have worked to use forward-slashes and quote escaping of the path.
