### ISSUE TITLE
Error when build .dylib

### ISSUE THREAD

**Issue by Malaik78** [usnistgov/REFPROP-cmake#39]
Hello,

I have a problem to build the .dylib for iOS.

The "PASS_FTN.FOR" is in my folder "fortran", like other as "CORE_ANC.FOR".

I don't understand why it doesn't build the "PASS_FTN.FOR.o" file and the .dylib...

Can you help me please ? :)

Thank you.

**Comment by ianhbell** [comment]
This build system is intended for REFPROP 9.1+.  For older verions, see https://github.com/jowr/librefprop.so
