### ISSUE TITLE
brewed python on macOS

### ISSUE THREAD

**Issue by adposition** [usnistgov/REFPROP-cmake#41]
``cmake --build .`` on macOS Majave with brewed python and vanilla system python failed because find_package (PythonInterp), called by ``cmake .. -DCMAKE_BUILD_TYPE=Release``, picked up the system python rather than the brewed python, as evident from an examination of CMakeCache.txt and build.make.

The solution was to force cmake to use the brewed python.
 
``cmake .. -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3``

**Comment by ianhbell** [comment]
Thanks, I'll add this info to the instructions

**Comment by ianhbell** [comment]
Closed by b5fd2ec2543035d74f5bbf91c8507fa3c3151c5f
