### ISSUE TITLE
“vaporpressure_bis” , unrecognized variable or function 

### ISSUE THREAD

**Issue by momengif** [usnistgov/REFPROP-cmake#42]
I have a prolem with 'vporpressure_bis' function if you could help!

Done with ODE solver
now extracting data
Unrecognized function or variable 'vaporpressure_bis'.

Error in Data_extraction (line 22)
nominal.pv1(z,:)=vaporpressure_bis(nominal.uv1(z,end), nominal.rhov1(z));

Error in runNominal (line 16)
Data_extraction;

Error in run (line 91)
evalin('caller', strcat(script, ';'));

**Comment by ianhbell** [comment]
Not a REFPROP function, don't think we can help with this one.
