### ISSUE TITLE
Error: could not load Cache on cmake build

### ISSUE THREAD

**Issue by ericksonla** [usnistgov/REFPROP-cmake#44]
I'm having trouble with a new install of REFPROP on OSX 10.15.7. Here is my traceback:
```
ericksonla@ericksonla build % cmake .. -DCMAKE_BUILD_TYPE=Release 
-- DEFSYM_FLAG: 
-- darwin
Missing from PASS_CMN_tokens:  ['ABFLSHdll', 'ALLPROPS0dll', 'ALLPROPS1dll', 'ALLPROPS20dll', 'ALLPROPSdll', 'CRTPNTdll', 'DEFL1dll', 'DERVPVTdll', 'DHFL1dll', 'DSD1dll', 'ERRMSGdll', 'FLAGSdll', 'GERG08dll', 'GETENUMdll', 'GETMODdll', 'GETREFDIRdll', 'HEATFRMdll', 'HMXORDERdll', 'HSFL1dll', 'MASSFLUXdll', 'MELTKdll', 'PASSCMNdll', 'PEFL1dll', 'PHI0dll', 'PHIDERVdll', 'PHIHMXdll', 'PHIKdll', 'PHIMIXdll', 'RDXHMXdll', 'REFPROP1dll', 'REFPROP2dll', 'REFPROPdll', 'RIEMdll', 'SATESTdll', 'SATGUESSdll', 'SETFLUIDSdll', 'SETMIXTUREdll', 'SETREFDIRdll', 'STNdll', 'TEFL1dll', 'THFL1dll', 'TSATPdll', 'TSFL1dll', 'VIRBCDdll', 'WMOLIdll']
Missing from REFPROP_lib.h: ['DPDDKdll', 'DPDTKdll', 'ACTVYdll', 'DOTFILLdll', 'OMEGAdll', 'ETAK0dll', 'ETAK1dll', 'ETAKRdll', 'ETAKBdll', 'TCXK0dll', 'TCXKBdll', 'TCXKCdll']

-- Path to libquadmath.a:/usr/local/Cellar/gcc/10.2.0/lib/gcc/10/gcc/x86_64-apple-darwin19/10.2.0/../../../libquadmath.a
-- Copied libquadmath.a here.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ericksonla/REFPROP-cmake
ericksonla@ericksonla build % cmake --build .
Error: could not load cache
```

Any advice here? Thanks!

**Comment by ericksonla** [comment]
This was with cmake 3.18.4. It looks like maybe this version wants you to build from the root directory (skip 'mkdir build; cd build'). That mostly worked (working through some unrelated problems now).

**Comment by ianhbell** [comment]
Can you please show all your shell output to get you to that point?  What version of REFPROP do you use? Something seems amiss in your configuration.

**Comment by ericksonla** [comment]
I closed my full output, unfortunately. I was in a hurry and wasn't being particularly careful. If that all seems wrong, it's probably safe to assume I just made a mistake.

**Comment by ianhbell** [comment]
Yes, I think you did something funny with how you setup your build.  I would recommend a clean rebuilt from scratch, following the steps one at a time.  I think that would work (hopefully).
