### ISSUE TITLE
REFPROP build on Ubuntu 18.04

### ISSUE THREAD

**Issue by zdoor** [usnistgov/REFPROP-cmake#48]
Hi Ian,

I ran into this error (header files)

[ 93%] Linking Fortran shared library librefprop.so
[ 93%] Built target refprop
Scanning dependencies of target REFPROP_H
[100%] About to build the REFPROP.h header file w/ /usr/bin/python;-u;/media/alex/data/HSH/REFPROP/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/media/alex/data/HSH/REFPROP/REFPROP-cmake/FORTRAN/DLLFILES;--python-exe;/usr/bin/python
Traceback (most recent call last):
File "/media/alex/data/HSH/REFPROP/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 2, in <module>
import subprocess, sys, six, os, re
ImportError: No module named six
CMakeFiles/REFPROP_H.dir/build.make:60: recipe for target 'REFPROP.h.stamp' failed
make[2]: *** [REFPROP.h.stamp] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/REFPROP_H.dir/all' failed
make[1]: *** [CMakeFiles/REFPROP_H.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

However six is available:
python -c "import six"

returns no errors.

When I copy the librefprop.so file into /usr/local/lib/python3.6/dist-packages manually I find the following error in ipython:

In [3]: from ctREFPROP.ctREFPROP import REFPROPFFunctionLibrary
---------------------------------------------------------------------------
ImportError Traceback (most recent call last)
<ipython-input-3-0ac89c393f7b> in <module>()
----> 1 from ctREFPROP.ctREFPROP import REFPROPFFunctionLibrary
ImportError: cannot import name 'REFPROPFFunctionLibrary' 

Can you help? Thanks in advance.

**Comment by ianhbell** [comment]
Can you please show all the build output you had from the beginning?  You seem to have different python interpreters being used for different stages.

**Comment by zdoor** [comment]
Ubuntu 18.04 has python 2.7 and python 3.6.9.

Will start over now

**Comment by ianhbell** [comment]
You might want to try setting Python executable path like for OSX: https://github.com/usnistgov/REFPROP-cmake#osx-notes

**Comment by zdoor** [comment]
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 7.5.0
-- Check for working Fortran compiler: /usr/bin/gfortran
-- Check for working Fortran compiler: /usr/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/gfortran supports Fortran 90
-- Checking whether /usr/bin/gfortran supports Fortran 90 -- yes
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- DEFSYM_FLAG: --using-defsym
-- linux2
Missing from PASS_CMN_tokens:  []
Missing from REFPROP_lib.h: []

-- Configuring done
-- Generating done
-- Build files have been written to: /media/alex/data/HSH/REFPROP/REFPROP-cmake/build

**Comment by zdoor** [comment]
Scanning dependencies of target refprop
[  6%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN/CORE_ANC.FOR.o
[ 12%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN/CORE_FEQ.FOR.o
[ 18%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN/CORE_PR.FOR.o
[ 25%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN/FLSH_SUB.FOR.o
[ 31%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN/MIX_HMX.FOR.o
[ 37%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN/PROP_SUB.FOR.o
[ 43%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN/REFPROP.FOR.o
/media/alex/data/HSH/REFPROP/REFPROP-cmake/FORTRAN/REFPROP.FOR:5589:72:

          if (ABS(iErrPrnt).eq.3) pause           !If your compiler complains about this line, just delete it.
                                                                        1
Warning: Deleted feature: PAUSE statement at (1)
[ 50%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN/SAT_SUB.FOR.o
[ 56%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN/SETUP.FOR.o
[ 62%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN/TRNSP.FOR.o
[ 68%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN/TRNS_TCX.FOR.o
[ 75%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN/TRNS_VIS.FOR.o
[ 81%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN/UTILITY.FOR.o
[ 87%] Building Fortran object CMakeFiles/refprop.dir/FORTRAN/DLLFILES/PASS_FTN.FOR.o
[ 93%] Linking Fortran shared library librefprop.so
[ 93%] Built target refprop
Scanning dependencies of target REFPROP_H
[100%] About to build the REFPROP.h header file w/ /usr/bin/python;-u;/media/alex/data/HSH/REFPROP/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/media/alex/data/HSH/REFPROP/REFPROP-cmake/FORTRAN/DLLFILES;--python-exe;/usr/bin/python
Traceback (most recent call last):
  File "/media/alex/data/HSH/REFPROP/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 2, in <module>
    import subprocess, sys, six, os, re
ImportError: No module named six
CMakeFiles/REFPROP_H.dir/build.make:60: recipe for target 'REFPROP.h.stamp' failed
make[2]: *** [REFPROP.h.stamp] Error 1
CMakeFiles/Makefile2:105: recipe for target 'CMakeFiles/REFPROP_H.dir/all' failed
make[1]: *** [CMakeFiles/REFPROP_H.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ianhbell** [comment]
Yes, use the PYTHON_EXECUTABLE variable to set the path to python 3.6.x and you should be in business.

**Comment by zdoor** [comment]
There it is. Same error. However when setting an absolute path I can work with it:
In [2]: import os
In [3]: import numpy as np
In [4]: from ctREFPROP.ctREFPROP import REFPROPFunctionLibrary
In [8]: RP1 = REFPROPFunctionLibrary(path, 'so')
In [10]: baseSI = RP1.GETENUMdll(0, "MOLAR BASE SI  ").iEnum
In [11]: iMass=0;iFlag=0
In [12]: r = RP1.REFPROPdll(r"AMMONIA.FLD", "TD","ETA",baseSI,iMass,iFlag,398.788,7044.7,[1.0]+[0.0]*19)
 print(r)
REFPROPdlloutput(z=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), Output=array('d', [1.7293356635438773e-05, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0, -9999990.0]), hUnits='Pa-s', iUCode=4294967286, x=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), y=array('d', [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), x3=array('d', [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]), q=1.0503910739792408, ierr=0, herr='')
In [14]: print(RP1.RPVersion())
******

**Comment by zdoor** [comment]
Great thank you. I shall. 
RPVersion() returns ******
I remember seeing that in the docs. I had to file a report? I forgot what it meant. Will look again.

**Comment by ianhbell** [comment]
It means you need to email me (ian.bell@nist.gov) to get a patch for 10.0.0.2
