### ISSUE TITLE
REFPROP 10 cmake issue

### ISSUE THREAD

**Issue by briannasheard** [usnistgov/REFPROP-cmake#49]
I am working from a Windows (365) computer, trying to access REFPROP 10 through excel functions. I have been following these instructions to set up links in my excel file that use the updated version of REFPROP. Am I on the right track here?

In following these instructions, and this is the error I am getting. I ran step 6 on Visual Basic Development Command Prompt. How can I resolve this?

REFPROP-cmake\build>cmake .. -DCMAKE_BUILD_TYPE=Release

-- The Fortran compiler identification is unknown
CMake Error at CMakeLists.txt:3 (enable_language):
  No CMAKE_Fortran_COMPILER could be found.

-- Configuring incomplete, errors occurred!
See also "C:/Users/bsheard001/REFPROP-cmake/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/bsheard001/REFPROP-cmake/build/CMakeFiles/CMakeError.log".

**Comment by ianhbell** [comment]
Actually none of this is required for you, thankfully.  Once you buy and install REFPROP 10, it includes the Excel interface and examples.  If you want updated versions of the interface, check out: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/Excel
