### ISSUE TITLE
Official build tool for refprop 10 DLL？

### ISSUE THREAD

**Issue by AnthonyChanMarvel** [usnistgov/REFPROP-cmake#51]
I tried to use MinGW (gcc version 8.1.0) to build refprop10, however the speed of HSFLSH calculation is about 5 times slower than official DLL(only HSFLSH calculation is slow)? I also tried to use VS community 2019 and Parallel Studio XE 2019 to build code, building is successful, however, when I use C++ to load DLL, it shows fortran error. Could you provide the official version of build tool?

**Comment by ianhbell** [comment]
I used REFPROP-cmake to build the DLL we released with 10.0.  But an older version of Intel Fortran ( think it was 2016 if I remember rightly).  What C++ error do you get?

Not surprising that MINGW builds are a bit slower.  There are often subtle (and sometimes not so subtle) differences in speeds between compilers.
