### ISSUE TITLE
Question about MACOS

### ISSUE THREAD

**Issue by trirex** [usnistgov/REFPROP-cmake#53]
Where do I place the folders that contain the property data for macOS?

**Comment by ianhbell** [comment]
It depends.  What are you trying to do? How are you interfacing with REFPROP, etc?

**Comment by trirex** [comment]
I would like to Use REFPROP with Python Version 3.9 (Jupyter Lab).

**Comment by ianhbell** [comment]
In that case, you just need to make sure that ``FLUIDS`` and ``MIXTURES`` folders are all sitting in the same folder as the shared library you build with https://github.com/usnistgov/REFPROP-cmake .  Then you pass that path to REFPROPFunctionLibrary and should also call SETPATHdll for good measure.

**Comment by trirex** [comment]
I have the project compiled for MACOS and it seems to be running.  I am not getting a reasonable return value for "print(RP.RPVersion())".  See example code and output in the attached file.  I'm concerned if RPVersion is not showing there could be other problems.  Do you have any advise or sample code I could try to verify its working as correctly?

[Question about MACOS · Issue #53 · usnistgov:REFPROP-cmake.pdf](https://github.com/usnistgov/REFPROP-cmake/files/6145994/Question.about.MACOS.Issue.53.usnistgov.REFPROP-cmake.pdf)

I am using NIST version 10

**Comment by ianhbell** [comment]
Please email me (ian.bell@nist.gov) for a tiny patch that fixes the **** coming from RPVersion.  Luckily that is not an indication of other major problems, just a mistake we made when releasing.
