### ISSUE TITLE
Error when compiling PASS_FTN.FOR

### ISSUE THREAD

**Issue by Architect0rr** [usnistgov/REFPROP-cmake#57]
I use REFPROP 7
After cmake --build .

`/REFPROP-cmake/FORTRAN/DLLFILES/PASS_FTN.FOR:19:6:`
`   19 |       dll_export SETUPdll`
`      |      1`
`Error: Unclassifiable statement at (1)`

**Comment by ianhbell** [comment]
REFPROP-cmake only works with REFPROP 9.1+. You can try with https://github.com/jowr/librefprop.so

**Comment by Architect0rr** [comment]
Sorry, thank you
