### ISSUE TITLE
error while compiling REFPROP

### ISSUE THREAD

**Issue by saha84** [usnistgov/REFPROP-cmake#6]
Hello,
As you mentioned in the issue https://github.com/CoolProp/CoolProp/issues/1303 , it's probably a problem within my system, but I don't know where is the problem exactly.

As for the version of the pre-requisites:

Python 3.5.2
cmake version 3.6.2
GNU Fortran (GCC) 6.2.1 20160830

**Comment by ianhbell** [comment]
Can you please email to ian.bell@nist.gov a zip file of your FORTRAN sources you are trying to compile? I can fire up a virtual machine with your files and debug the problems on my end.

Also, please note your operating system.

**Comment by saha84** [comment]
My operating system information :

OS: Arch Linux 
 Kernel: x86_64 Linux 4.8.4-1-ARCH
 Shell: zsh 5.2

**Comment by ianhbell** [comment]
Hmm worked fine on ubuntu, I did:
```
cmake .. -DREFPROP_FORTRAN_PATH=/media/sf_H_DRIVE/FORTRAN
cmake --build .
```
where the path is set to the unzipped folder of sources you sent me.
More info:
```
ian@ian-VirtualBox:~/Code/REFPROP-cmake/externals/REFPROP-headers$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

ian@ian-VirtualBox:~/Code/REFPROP-cmake/externals/REFPROP-headers$ gfortran --version
GNU Fortran (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING

ian@ian-VirtualBox:~/Code/REFPROP-cmake/externals/REFPROP-headers$ cmake --version
cmake version 2.8.12.2

```

**Comment by saha84** [comment]
That's weird, could it be because that my gcc and gfortran are a newer version (6.2.1)?

I will try to downgrade them and see the result

**Comment by ianhbell** [comment]
Might be - in your source files it tries to include ``commons.for``, which for a non-case-sensitive operating system like windows is the same as ``COMMONS.FOR``.  Perhaps gcc 4.6.1 matches include files independent of case (which would make sense since fortran is barely case sensitive).  And then 6.2.1 is more pedantic and doesn't accept that file ?

Also, you might want to try the 9.1.1 sources that I have emailed to you.

**Comment by saha84** [comment]
Even with the 9.1.1 the complition dosen't succeed, but the errors are a bit different:

**with 9.1:**
-- DEFSYM_FLAG: --using-defsym
-- linux
Missing from PASS_CMN_tokens:  ['DHFL1dll', 'PASSCMN', 'PHI0dll']
Missing from REFPROP_lib.h: ['SETNCdll', 'MAXTdll', 'MAXPdll', 'B12dll', 'VIRBAdll', 'VIRCAdll', 'HEATdll', 'SATTESTdll', 'SATPESTdll', 'PSATKdll', 'DLSATKdll', 'DVSATKdll', 'TSATDdll', 'TPRHOPRdll', 'DQFL2dll', 'CSTARdll', 'LIQSPNDLdll', 'VAPSPNDLdll', 'OMEGAdll', 'ETAK0dll', 'ETAK1dll', 'ETAKRdll', 'ETAKBdll', 'TCXK0dll', 'TCXKBdll', 'TCXKCdll', 'IDCRVdll', 'BLCRVdll', 'JTCRVdll', 'JICRVdll']

**with 9.1.1**
-- DEFSYM_FLAG: --using-defsym
-- linux

Missing from PASS_CMN_tokens:  ['PASSCMN']
Missing from REFPROP_lib.h: ['GETMODdll', 'SETNCdll', 'MAXTdll', 'MAXPdll', 'B12dll', 'VIRBAdll', 'VIRCAdll', 'RIEMdll', 'HEATdll', 'HEATFRMdll', 'SATTESTdll', 'SATPESTdll', 'PSATKdll', 'DLSATKdll', 'DVSATKdll', 'TSATDdll', 'TPRHOPRdll', 'DQFL2dll', 'CSTARdll', 'PEFL1dll', 'THFL1dll', 'TSFL1dll', 'TEFL1dll', 'HSFL1dll', 'RDXHMXdll', 'DEFL1dll', 'LIQSPNDLdll', 'VAPSPNDLdll', 'SATGUESSdll', 'IDCRVdll', 'BLCRVdll', 'JTCRVdll', 'JICRVdll', 'DERVPVTdll']

**Comment by ianhbell** [comment]
Those are just warnings, how about error messages?

**Comment by saha84** [comment]
OK it worked fine

Now I just need to put the librefprop.so in /opt/refprop?

**Comment by ianhbell** [comment]
Yup, that should do it.  I'll see if I can figure out how to make newer gcc versions not fail like yours did.

**Comment by saha84** [comment]
thank you very much,
should I close this issue?

**Comment by ianhbell** [comment]
I'm going to investigate whether I can fix this issue.

**Comment by jsbahamonde** [comment]
Dear Ian,
Need your help. I am using the fortran files from RefProp 9.1. I have followed the instructions, this is the corresponding history:

![screenshot from 2017-02-06 10-29-56](https://cloud.githubusercontent.com/assets/10710216/22641517/55b1492e-ec57-11e6-986e-e0ddcd6047a4.png)
As you can see, the error comes after "cmake --build . ":
" Can't open included file 'commons.for'"

Hope you can help me. Thanks for your time,
Sebastian

**Comment by ianhbell** [comment]
The "solution" is to replace all the calls to commons.for with COMMONS.FOR in the FORTRAN code.  Alternatively, to email me (ian.bell@nist.gov) and I can send you the source for 9.1.1, which compiles reliably on linux.

**Comment by SBahamonde** [comment]
Thanks! It worked fine with the 9.1.1 version
