### ISSUE TITLE
ValueError at "cmake --build ." step

### ISSUE THREAD

**Issue by downtRoddenn** [usnistgov/REFPROP-cmake#60]
Good day sir Ian,
I hope this concern finds you in good health.
I am trying to install REFPROP 9.1 on my Ubuntu 20.04 and I keep running into a ValueError on the last step.
If you may be of assistance, your efforts are very much appreciated.
kudos for your amazing work!

`rodden@rodden-Lenovo-ideapad-130-15IKB:~/REFPROP-cmake/build$ cmake .. -DCMAKE_BUILD_TYPE=Release
-- DEFSYM_FLAG: --using-defsym
-- linux
Missing from PASS_CMN_tokens:  ['ABFLSHdll', 'ABFLASHdll', 'ALLPROPS0dll', 'ALLPROPS1dll', 'ALLPROPS20dll', 'ALLPROPSdll', 'CRTPNTdll', 'DEFL1dll', 'DERVPVTdll', 'DHFL1dll', 'DSD1dll', 'ERRMSGdll', 'FLAGSdll', 'GERG08dll', 'GETENUMdll', 'GETMODdll', 'GETREFDIRdll', 'HEATFRMdll', 'HMXORDERdll', 'HSFL1dll', 'MASSFLUXdll', 'MELTKdll', 'PASSCMNdll', 'PEFL1dll', 'PHI0dll', 'PHIDERVdll', 'PHIHMXdll', 'PHIKdll', 'PHIMIXdll', 'RDXHMXdll', 'REFPROP1dll', 'REFPROP2dll', 'REFPROPdll', 'RIEMdll', 'SATESTdll', 'SATGUESSdll', 'SETFLUIDSdll', 'SETMIXTUREdll', 'SETREFDIRdll', 'STNdll', 'TEFL1dll', 'THFL1dll', 'TSATPdll', 'TSFL1dll', 'VIRBCDdll', 'VIRBCD12dll', 'VIRTAUdll', 'WMOLIdll']
Missing from REFPROP_lib.h: ['DPDDKdll', 'DPDTKdll', 'ACTVYdll', 'DOTFILLdll', 'OMEGAdll', 'ETAK0dll', 'ETAK1dll', 'ETAKRdll', 'ETAKBdll', 'TCXK0dll', 'TCXKBdll', 'TCXKCdll']

-- Configuring done
-- Generating done
-- Build files have been written to: /home/rodden/REFPROP-cmake/build
rodden@rodden-Lenovo-ideapad-130-15IKB:~/REFPROP-cmake/build$ cmake --build .
[  3%] About to build the REFPROP.h header file w/ /usr/bin/python3.8;-u;/home/rodden/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/home/rodden/REFPROP-cmake/fortran;--python-exe;/usr/bin/python3.8
Writing the .pyf file with numpy.f2py, please be patient...
About to run: /usr/bin/python3.8 -m numpy.f2py --quiet --no-lower -h REFPROP.pyf /home/rodden/REFPROP-cmake/fortran/PASS_FTN.FOR
numpy version: 1.22.1
Traceback (most recent call last):
  File "/home/rodden/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 184, in <module>
    dd = generate_function_dict('REFPROP.pyf')
  File "/home/rodden/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 138, in generate_function_dict
    output = find_subroutine(lines, istart)
  File "/home/rodden/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 98, in find_subroutine
    raise ValueError(lines[istart + 1 + offset].strip())
ValueError: real dimension(ncmax) :: x0
make[2]: *** [CMakeFiles/REFPROP_H.dir/build.make:61: REFPROP.h.stamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/REFPROP_H.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`
Thank you for your time,
Rodden

**Comment by ianhbell** [comment]
Are you sure it is really 9.1? I built 9.1 on my side with this setup without problem.  Let me test on ubuntu though to make sure I haven't broken something.  But really, you should upgrade to version 10.

**Comment by ianhbell** [comment]
I have the same problem on my side.  I think it might be a bug in f2py, which is quite fragile.

It would be helpful also to see the output from the config step too to see what version of numpy you have

**Comment by downtRoddenn** [comment]
thank you for the immediate reply.

as much as I would prefer v10, v9.1 is the recommended version for my ongoing university class: power plant design.

my numpy version is 1.22.1

**Comment by ianhbell** [comment]
Can you try with older versions of numpy? There seems to be a bug in f2py dying on valid fortran code

**Comment by downtRoddenn** [comment]
I will try sir. I will get back to you as soon as possible. btw, which numpy version would you recommend?

**Comment by ianhbell** [comment]
Not sure, maybe pre-1.0?

**Comment by ianhbell** [comment]
Come to think of it, do you need the header? It is optional, and you can disable its construction: https://github.com/usnistgov/REFPROP-cmake#general-notes

**Comment by downtRoddenn** [comment]
sir, it seems cmake requires python2 and I feel I am not fit to operate this. I manage to drop my numpy upto 1.16.5, and it didnt work as indended. so I might just try a different approach to experience REFPROP all together.

Thank you so much for your time.

**Comment by ianhbell** [comment]
Definitely does not require python2. I use python3 all the time.  You might need to delete your build folder and try again fresh

**Comment by downtRoddenn** [comment]
sir I tried remaking the build folder after removing python2. and i got a different ValueError this time.

> rodden@rodden-Lenovo-ideapad-130-15IKB:~/REFPROP-cmake/build$ cmake --build .
> Scanning dependencies of target REFPROP_H
> [  3%] About to build the REFPROP.h header file w/ /usr/bin/python3.8;-u;/home/rodden/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/home/rodden/REFPROP-cmake/build/FORTRAN_temp;--python-exe;/usr/bin/python3.8
> Writing the .pyf file with numpy.f2py, please be patient...
> About to run: /usr/bin/python3.8 -m numpy.f2py --quiet --no-lower -h REFPROP.pyf /home/rodden/REFPROP-cmake/build/FORTRAN_temp/PASS_FTN.FOR
> numpy version: 1.22.2
> Traceback (most recent call last):
>   File "/home/rodden/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 183, in <module>
>     generate_interface_file(valid_paths[0], 'REFPROP.pyf', python_exe = args.python_exe[0])
>   File "/home/rodden/REFPROP-cmake/externals/REFPROP-headers/generate_header.py", line 26, in generate_interface_file
>     raise ValueError('Unable to call f2py successfully: '+str(err))
> ValueError: Unable to call f2py successfully: b'Traceback (most recent call last):\n  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main\n    return _run_code(code, main_globals, None,\n  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code\n    exec(code, run_globals)\n  File "/home/rodden/.local/lib/python3.8/site-packages/numpy/f2py/__main__.py", line 5, in <module>\n    main()\n  File "/home/rodden/.local/lib/python3.8/site-packages/numpy/f2py/f2py2e.py", line 693, in main\n    run_main(sys.argv[1:])\n  File "/home/rodden/.local/lib/python3.8/site-packages/numpy/f2py/f2py2e.py", line 430, in run_main\n    postlist = callcrackfortran(files, options)\n  File "/home/rodden/.local/lib/python3.8/site-packages/numpy/f2py/f2py2e.py", line 333, in callcrackfortran\n    postlist = crackfortran.crackfortran(files)\n  File "/home/rodden/.local/lib/python3.8/site-packages/numpy/f2py/crackfortran.py", line 3206, in crackfortran\n    readfortrancode(files, crackline)\n  File "/home/rodden/.local/lib/python3.8/site-packages/numpy/f2py/crackfortran.py", line 507, in readfortrancode\n    readfortrancode(fn1, dowithline=dowithline, istop=0)\n  File "/home/rodden/.local/lib/python3.8/site-packages/numpy/f2py/crackfortran.py", line 513, in readfortrancode\n    dowithline(finalline)\n  File "/home/rodden/.local/lib/python3.8/site-packages/numpy/f2py/crackfortran.py", line 809, in crackline\n    analyzeline(m, pat[1], line)\n  File "/home/rodden/.local/lib/python3.8/site-packages/numpy/f2py/crackfortran.py", line 1200, in analyzeline\n    for e in markoutercomma(ll).split(\'@,@\'):\n  File "/home/rodden/.local/lib/python3.8/site-packages/numpy/f2py/crackfortran.py", line 846, in markoutercomma\n    assert not f, repr((f, line, l))\nAssertionError: (-1, \'ncmax=20)     !max number of components in mixtur\', \'ncmax=20)     !max number of components in mixtur\')\n'
> make[2]: *** [CMakeFiles/REFPROP_H.dir/build.make:61: REFPROP.h.stamp] Error 1
> make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/REFPROP_H.dir/all] Error 2
> make: *** [Makefile:84: all] Error 2
>

**Comment by ianhbell** [comment]
As I mentioned, you should disable the header generation with ``-DREFPROP_NO_NUMPY=ON`` to the first config step

**Comment by downtRoddenn** [comment]
thank you so much sir. it says 100% Built target refprop.

last question sir, in the instructions,
once the shared library has been build, does the "it" in "need to place it somewhere", refers to the build directory or a certain file in the directory?

**Comment by ianhbell** [comment]
You should place the build binary file in the folder that contains the FLUIDS and MIXTURES folders.

**Comment by downtRoddenn** [comment]
oh. I might have misunderstood. To run REFPROP on a linux machine, it still needs a virtual windows machine?

**Comment by ianhbell** [comment]
No, but you do still need the FLUIDS and MIXTURES files on your linux machine

**Comment by downtRoddenn** [comment]
So basically, now I just have to bundle the FLUIDS and MIXTURES folders in one folder with librefprop.so and place it in ~usr/lib?

**Comment by ianhbell** [comment]
Yes, or any other location you like, and specify that location to SETPATHdll when you load the library

**Comment by downtRoddenn** [comment]
Thank you so much again sir for all your help
