### ISSUE TITLE
Issues with building version 10 on Mac

### ISSUE THREAD

**Issue by marwoy** [usnistgov/REFPROP-cmake#62]
Hello,

I have some issues with building version 10 on my Mac (Version 11.6.2). So here's what I'm doing:

I copied the FORTRAN folder into the cloned repository and followed the instructions.
Running 
`cmake .. -DCMAKE_BUILD_TYPE=Release`
first gives me the error
`
CMake Error at CMakeLists.txt:213 (message):
  PASS_FTN.FOR was found in both the root folder of sources as well as in the
  DLLFILES subfolder.  Please delete one of them and try again.
`

So I deleted one of those files (It doesn't matter which one I delete, at the end I always get the same result).

Afterwards the build command succeeds even though I get some text shown:
`
Missing from PASS_CMN_tokens:  ['ABFLSHdll', 'ABFLASHdll', 'ALLPROPS0dll', 'ALLPROPS1dll', 'ALLPROPS20dll', 'ALLPROPSdll', 'CRTPNTdll', 'DEFL1dll', 'DERVPVTdll', 'DHFL1dll', 'DSD1dll', 'ERRMSGdll', 'FLAGSdll', 'GERG08dll', 'GETENUMdll', 'GETMODdll', 'GETREFDIRdll', 'HEATFRMdll', 'HMXORDERdll', 'HSFL1dll', 'MASSFLUXdll', 'MELTKdll', 'PASSCMNdll', 'PEFL1dll', 'PHI0dll', 'PHIDERVdll', 'PHIHMXdll', 'PHIKdll', 'PHIMIXdll', 'RDXHMXdll', 'REFPROP1dll', 'REFPROP2dll', 'REFPROPdll', 'RIEMdll', 'SATESTdll', 'SATGUESSdll', 'SETFLUIDSdll', 'SETMIXTUREdll', 'SETREFDIRdll', 'STNdll', 'TEFL1dll', 'THFL1dll', 'TSATPdll', 'TSFL1dll', 'VIRBCDdll', 'VIRBCD12dll', 'VIRTAUdll', 'WMOLIdll']
Missing from REFPROP_lib.h: ['DPDDKdll', 'DPDTKdll', 'ACTVYdll', 'DOTFILLdll', 'OMEGAdll', 'ETAK0dll', 'ETAK1dll', 'ETAKRdll', 'ETAKBdll', 'TCXK0dll', 'TCXKBdll', 'TCXKCdll']
`

When I now do `cmake -- build .` I get
`
REFPROP-cmake/build/FORTRAN_temp/CORE_ANC.FOR:76: Error: Can't open included file 'COMMONS.INC'
make[2]: *** [CMakeFiles/refprop.dir/FORTRAN_temp/CORE_ANC.FOR.o] Error 1
make[1]: *** [CMakeFiles/refprop.dir/all] Error 2
make: *** [all] Error 2
`

If I then redo `cmake .. -DCMAKE_BUILD_TYPE=Release` and `cmake -- build .` It builds almost until the end but I get
`
[ 96%] Linking Fortran shared library librefprop.dylib
Undefined symbols for architecture x86_64:
  "_actvy_", referenced from:
      _actvydll_ in PASS_FTN.FOR.o
  "_cbrtx_", referenced from:
      _delhsv_ in TRNS_ECS.FOR.o
`
There are some more lines afterwards with undefined symbols but I hope this might already tell you what my issue might be.

I'm not that familiar with cmake so I would be very happy if you could help me with this.

Thanks in advance!

**Comment by ianhbell** [comment]
Something is messed up in your configuration because you should not have this issue with ``PASS_FTN.FOR``.  It is also recommended to not move the FORTRAN folder, rather add the argument ``-DREFPROP_FORTRAN_PATH=<PATH>``.

I compiled REFPROP on my colleagues' OSX machine and it worked flawlessly.

**Comment by marwoy** [comment]
Thanks a lot for your fast reply.
So I reveived the .exe of Version 10, then I installed it on a Windows VM. If you say I should not copy the FORTRAN folder, but add the path, this would mean I copy the whole REFPROP folder from my windows VM to my Mac, is this correct?
And if you say "you should not have this issue with PASS_FTN.FOR" do you mean there should not be two files for this? I will recheck my REFPROP installation on the Windows VM and see if I can fix it.

**Comment by marwoy** [comment]
You were right, something was broken with my installation. I needed to delete the REFPROP application and reinstall it and now everything is working flawlessly.
Thanks a lot for your immediate support.
