### ISSUE TITLE
CMake Error at CMakeLists.txt:279 (add_library)

### ISSUE THREAD

**Issue by fjcheng** [usnistgov/REFPROP-cmake#65]
[variant] Loaded new set of variants
[kit] Successfully loaded 5 kits from C:\Users\AppData\Local\CMakeTools\cmake-tools-kits.json
[proc] Executing command: "D:\Program Files\mingw64\bin\gcc.exe" -v
[main] Configuring folder: REFPROP-cmake-master 
[proc] Executing command: "D:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Release "-DCMAKE_C_COMPILER:FILEPATH=D:\Program Files\mingw64\bin\gcc.exe" "-DCMAKE_CXX_COMPILER:FILEPATH=D:\Program Files\mingw64\bin\g++.exe" -Sc:/Users/Desktop/flask_demo/REFPROP/REFPROP-cmake-master -Bc:/Users/Desktop/flask_demo/REFPROP/REFPROP-cmake-master/build -G "MinGW Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] -- The C compiler identification is GNU 8.1.0
[cmake] -- The CXX compiler identification is GNU 8.1.0
[cmake] -- Detecting C compiler ABI info
[cmake] -- Detecting C compiler ABI info - done
[cmake] -- Check for working C compiler: D:/Program Files/mingw64/bin/gcc.exe - skipped
[cmake] -- Detecting C compile features
[cmake] -- Detecting C compile features - done
[cmake] -- Detecting CXX compiler ABI info
[cmake] -- Detecting CXX compiler ABI info - done
[cmake] -- Check for working CXX compiler: D:/Program Files/mingw64/bin/g++.exe - skipped
[cmake] -- Detecting CXX compile features
[cmake] -- Detecting CXX compile features - done
[cmake] -- The Fortran compiler identification is GNU 8.1.0
[cmake] -- Detecting Fortran compiler ABI info
[cmake] -- Detecting Fortran compiler ABI info - done
[cmake] -- Check for working Fortran compiler: D:/Program Files/mingw64/bin/gfortran.exe - skipped
[cmake] -- Found PythonInterp: D:/Program Files/Python39/python.exe (found version "3.9.11") 
[cmake] -- DEFSYM_FLAG: --using-defsym
[cmake] -- Path to libquadmath.a:D:/Program Files/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/libquadmath.a
[cmake] -- Copied libquadmath.a here.
[cmake] -- REFPROP version <= 9.1 identified by presence of include "'commons.for'"; copying locally and fixing include statement
[cmake] -- Fixing of FORTRAN files complete. Compilation ready.
[cmake] -- Set REFPROP_FORTRAN_PATH to C:/Users/Desktop/flask_demo/REFPROP/REFPROP-cmake-master/build/FORTRAN_temp
[cmake] -- Configuring done
[cmake] CMake Error at CMakeLists.txt:279 (add_library):
[cmake]   Cannot find source file:
[cmake] 
[cmake]     C:/Users/Desktop/flask_demo/REFPROP/REFPROP-cmake-master/build/REFPROP.DEF
[cmake] 
[cmake]   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
[cmake]   .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
[cmake] 
[cmake] 
[cmake] CMake Error at CMakeLists.txt:279 (add_library):
[cmake]   No SOURCES given to target: REFPRP64
[cmake] 
[cmake] 
[cmake] CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by ianhbell** [comment]
Is the DEF file generated? Looks like you are using cmake build tools in VS Code on windows with mingw. I haven't tried that combination out before. Can you try in the shell without all the VS Code trappings to make sure the mingw compilation is in general working for you?
