### ISSUE TITLE
Cmake Error at CMakeLists.txt - M1 Macbook Pro

### ISSUE THREAD

**Issue by BaranKaypakoglu** [usnistgov/REFPROP-cmake#66]
I followed the instructions and this is what I am receiving:

baran@Barans-MacBook-Pro build % cmake .. -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE:FILEPATH=/usr/local/bin/python3
-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 11.2.0
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag - yes
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /opt/homebrew/bin/gfortran - skipped
-- Found PythonInterp: /usr/local/bin/python3  
-- DEFSYM_FLAG: 
-- 
CMake Error at CMakeLists.txt:153 (file):
  file failed to open for reading (No such file or directory):

    /Users/baran/REFPROP-cmake/build/aliases_string.txt

-- Path to libquadmath.a:libquadmath.a
CMake Error at CMakeLists.txt:173 (file):
  file COPY cannot find "/Users/baran/REFPROP-cmake/libquadmath.a": No such
  file or directory.

-- Copied libquadmath.a here.
-- Configuring incomplete, errors occurred!

**Comment by ianhbell** [comment]
See #64

**Comment by BaranKaypakoglu** [comment]
Yes Ian but I could not do it. It looks like all these people know more or
less what they are doing. I am no programmer. Perhaps some more clear
instruction would be helpful.

**Comment by ianhbell** [comment]
We don't have a working solution for M1 yet, unfortunately. And I don't have access to an M1 either.

**Comment by ianhbell** [comment]
It is working for me, I use the Anaconda python that is native arm64 compiled, and the modern build systems work just fine with this setup.
