### ISSUE TITLE
Installing Refprop 10 on Mac M1 (OSX with Office 365)

### ISSUE THREAD

**Issue by matttah** [usnistgov/REFPROP-cmake#67]
I have followed the instructions given on ( https://github.com/usnistgov/REFPROP-cmake ) to build "librefprop.dylib". 

Below is the output message:
----------------------------------------------------------------------------------------------
-- The C compiler identification is AppleClang 13.1.6.13160021
-- The CXX compiler identification is AppleClang 13.1.6.13160021
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is GNU 11.3.0
-- Checking whether Fortran compiler has -isysroot
-- Checking whether Fortran compiler has -isysroot - yes
-- Checking whether Fortran compiler supports OSX deployment target flag
-- Checking whether Fortran compiler supports OSX deployment target flag - yes
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /opt/homebrew/bin/gfortran - skipped
-- Found PythonInterp: /usr/local/bin/python3 (found version "3.9.13") 
-- DEFSYM_FLAG: 
-- darwin
Missing from PASS_CMN_tokens:  ['ABFLASHdll', 'VIRBCD12dll', 'VIRTAUdll']
Missing from REFPROP_lib.h: []

-- Path to libquadmath.a:/opt/homebrew/Cellar/gcc/11.3.0_1/bin/../lib/gcc/11/gcc/aarch64-apple-darwin21/11/../../../libquadmath.a
-- Copied libquadmath.a here.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/matt/REFPROP-cmake/build
--------------------------------------------------------------------------------

It doesn't generate the "librefprop.dylib" file. I appreciate if someone can help!

**Comment by ianhbell** [comment]
See #66

**Comment by ianhbell** [comment]
I don't have access to an M1 :(

**Comment by matttah** [comment]
Hello Ian, 
After spending few hours, I could mange to get it to the point that generates all FOR.o files. But when it comes to linking fortran libraries it fails to generate librefprop.dylib. 

Please see the error :

----------------------------
Scanning dependencies of target refprop
[  6%] Building Fortran object CMakeFiles/refprop.dir/users/matt/REFPROP/FORTRAN/CORE_ANC.FOR.o
[ 12%] Building Fortran object CMakeFiles/refprop.dir/users/matt/REFPROP/FORTRAN/CORE_FEQ.FOR.o
[ 18%] Building Fortran object CMakeFiles/refprop.dir/users/matt/REFPROP/FORTRAN/CORE_PR.FOR.o
[ 25%] Building Fortran object CMakeFiles/refprop.dir/users/matt/REFPROP/FORTRAN/FLSH_SUB.FOR.o
[ 31%] Building Fortran object CMakeFiles/refprop.dir/users/matt/REFPROP/FORTRAN/MIX_HMX.FOR.o
[ 37%] Building Fortran object CMakeFiles/refprop.dir/users/matt/REFPROP/FORTRAN/PROP_SUB.FOR.o
[ 43%] Building Fortran object CMakeFiles/refprop.dir/users/matt/REFPROP/FORTRAN/REFPROP.FOR.o
/users/matt/REFPROP/FORTRAN/REFPROP.FOR:5589:72:

 5589 |          if (ABS(iErrPrnt).eq.3) pause           !If your compiler complains about this line, just delete it.
      |                                                                        1
Warning: Deleted feature: PAUSE statement at (1)
[ 50%] Building Fortran object CMakeFiles/refprop.dir/users/matt/REFPROP/FORTRAN/SAT_SUB.FOR.o
[ 56%] Building Fortran object CMakeFiles/refprop.dir/users/matt/REFPROP/FORTRAN/SETUP.FOR.o
[ 62%] Building Fortran object CMakeFiles/refprop.dir/users/matt/REFPROP/FORTRAN/TRNSP.FOR.o
[ 68%] Building Fortran object CMakeFiles/refprop.dir/users/matt/REFPROP/FORTRAN/TRNS_TCX.FOR.o
[ 75%] Building Fortran object CMakeFiles/refprop.dir/users/matt/REFPROP/FORTRAN/TRNS_VIS.FOR.o
[ 81%] Building Fortran object CMakeFiles/refprop.dir/users/matt/REFPROP/FORTRAN/UTILITY.FOR.o
[ 87%] Building Fortran object CMakeFiles/refprop.dir/users/matt/REFPROP/FORTRAN/DLLFILES/PASS_FTN.FOR.o
[ 93%] Linking Fortran shared library librefprop.dylib

gfortran: error: conflicting code generation switches
make[2]: *** [librefprop.dylib] Error 1
make[1]: *** [CMakeFiles/refprop.dir/all] Error 2
make: *** [all] Error 2

**Comment by bbradbury** [comment]
Hey @ianhbell - I'd be happy to get you access to a cloud instance of an M1 mac if that would help this effort. We are building refprop across platforms internally and if you were able to help us find our a way a bit that would be SUPER helpful. I'll send a note to the email address in your profile.

**Comment by ianhbell** [comment]
Does this M1 have also graphical access? That would be really helpful to test out Excel.  Otherwise I can test a lot of other stuff at the command line.

**Comment by bbradbury** [comment]
Yup!

**Comment by ianhbell** [comment]
In that case, please send me the email.

**Comment by bbradbury** [comment]
Done!

**Comment by bbradbury** [comment]
Hey Ian - unbelievably, it looks like Microsoft is missing an IPv6 reverse DNS record and the email is bouncing because of that - I will send you a note from my personal mail and see if that will get a friendlier response from the mail servers

**Comment by JeffSolo** [comment]
@ianhbell I had the same issue on an M1 - 
```
Linking Fortran shared library librefprop.dylib
gfortran error: conflicting code generation switches
```

It seems that the culprit is this line in the cmake file:
`set(REFPROP_LINK_FLAGS "${REFPROP_LINK_FLAGS} -static -static-libgfortran -static-libgcc ")`
If I remove the `-static` flag it builds without error.

**Comment by ianhbell** [comment]
Update: it *is* possible to get native arm64 binaries.
