### ISSUE TITLE
cmake error while building the library at 60%

### ISSUE THREAD

**Issue by Ali91en** [usnistgov/REFPROP-cmake#69]
hello everyone, I have a problem when I want to build the library for REFPROP. In the last step of REFPROP-cmake when I use command : 
`make --build .`
I face with this error at 60%:

`[60%] Building Fortran object CMakeFiles/refprop.dir/fortran/PASS_FTN.FOR.o
/Users/***/REFPROP-cmake/fortran/PASS_FTN.FOR:4:7:`
`    4 |       dll_export RPVersion
      |       1`
`Error: Unclassifiable statement at (1)`
`make[2]: *** [CMakeFiles/refprop.dir/fortran/PASS_FTN.FOR.o] Error 1`
`make[1]: *** [CMakeFiles/refprop.dir/all] Error 2`
`make: *** [all] Error 2`

**Comment by ianhbell** [comment]
What operating system, REFPROP version, etc? Please show the full build log (sanitized as you like)

**Comment by ianhbell** [comment]
And compiler

**Comment by Ali91en** [comment]
> What operating system, REFPROP version, etc? Please show the full build log (sanitized as you like)

Thank you for replying
I'm using Mac OS 12.4 (Intel), REFPROP 9, compiler gFortran12.1

cMakeOutput.log:
[log.log](https://github.com/usnistgov/REFPROP-cmake/files/9151143/log.log)

**Comment by ianhbell** [comment]
Please see the other issues on this repo regarding M1 chips.

**Comment by ianhbell** [comment]
Also, REFPROP 9 is no longer supported, please upgrade to at least 9.1, but better 10.0

**Comment by ianhbell** [comment]
The command prompt information is more useful for debugging as it collects the most important information
