### ISSUE TITLE
Installation failure on debian jessie

### ISSUE THREAD

**Issue by ericksonla** [usnistgov/REFPROP-cmake#7]
I'm trying to build librefprop.so on debian jessie (on a Raspberry Pi) and not having success. cmake reported success and produced a file called librefprop.so. I moved that file to my shared libraries folder (/usr/lib). I continued getting the `Initialize failed for backend "REFPROP"... error: Could not load these fluids: METHANOL|WATER` error when trying to call PropsSI with REFPROP fluids.

I have a couple theories:
1. I previously found (issue #2) that the build didn't work with gfortran 4.9. When I compiled this time, I got an enormous number of warnings (unfortunately since lost) that didn't seem to be critical. 4.9 is unfortunately the [highest version available on debian jessie](https://packages.debian.org/jessie/gfortran). Is it possible that the build would succeed but create an unusable library?
2. I'm not putting the library in the right place. Per issue #3, I think the library belongs in /usr/lib, but I'm not real sure. I've tried several other places but those all give me an error indicating they couldn't find the library.
3. I had some issues with the make file wanting lowercase files names when my refprop distribution had uppercase file names. Could this have passed through the build stage and this is the problem I'm seeing?

Any suggestions on what I should be trying to get this working?

**Comment by ericksonla** [comment]
No need to spend time on this if its not interesting for other people. I got the library built using the old librefprop.so makefile method.

**Comment by ianhbell** [comment]
I think you want to put librefprop.so and the fluids and mixtures directories in /opt/refprop, that is the default place that CoolProp will look for it.  Alternatively, you can set the path that is used: http://www.coolprop.org/coolprop/REFPROP.html#path-issues

Can you please provide a full build log?  

I'd like to get this working as close to 100% of the time as I can.  Or at least providing useful error messages when not.

Re: point 3, the cmake workflow should always use and expect uppercase names.

**Comment by ericksonla** [comment]
What exactly are you looking for in the build log? I unfortunately lost the terminal output. Is the CMakeOutput.log what you're looking for?

**Comment by ianhbell** [comment]
Yup, I would like to be able to see what versions of cmake/fortran, etc. were used.

**Comment by ianhbell** [comment]
I did a build on my debian jessie x64 virtual and it worked fine with gfortran 4.9, cmake 3.0.2, etc.

**Comment by ianhbell** [comment]
I'd be interested to have you try again and show all commands and output from the console.

**Comment by ericksonla** [comment]
Our setups are almost identical but the Raspberry Pi is 32 bit, not 64. Could that cause the problem?

I'll email you the complete build log once in finishes... it takes a while.

**Comment by ianhbell** [comment]
I suppose it could...  More likely the ARM part is the problem.

**Comment by ibell** [comment]
My Raspberry PI seems to be dead - or at least I can't get any output from it :(
