### ISSUE TITLE
forrtl: severe (268) - What version of FORTRAN files needed for build?

### ISSUE THREAD

**Issue by ScottALang** [usnistgov/REFPROP-cmake#71]
Hi,

I have been struggling to build a successful DLL.

My most recent attempt I did on a new install with
- Visual Studio 2022 17.3.2
- Intel Fortran 2022.1.0
- cmake 3.24.1
- python 3.10.5; six 1.16.0; numpy 1.23.2
- NIST FORTRAN files dated 6/4/2018

I build with
```
cmake .. -DCMAKE_BUILD_TYPE=Release -DREFPROP_DYNAMIC_RUNTIME=ON
cmake --build .
```
which completes without errors.

Here is my very simple C# test application: 
```
using System.Runtime.InteropServices;

const string DLL_PATH = "C:\\Users\\Scott\\source\\repos\\REFPROP Test\\REFPROP Test\\bin\\REFPRP64.DLL";
const string FLUIDS_PATH = "C:\\Users\\Scott\\source\\repos\\REFPROP Test\\REFPROP Test\\bin\\FLUIDS";

[DllImport(DLL_PATH)]
static extern void SETPATHdll(string hpth, int hpthLength);

[DllImport(DLL_PATH)]
static extern void SETFLUIDSdll(string hFld, ref int ierr, int hFldLength);

[DllImport(DLL_PATH)]
static extern void TPRHOdll(ref double T, ref double P, double z, ref int kph, ref int kguess, ref double D, ref int ierr, string herr);

SETPATHdll(FLUIDS_PATH, FLUIDS_PATH.Length);

string fluidName = "WATER.FLD";
int errorFlag = 0;
SETFLUIDSdll(fluidName, ref errorFlag, fluidName.Length);
Console.WriteLine("SETFLUIDSdll errorFlag " + errorFlag.ToString());

double T = 300;
double P = 100;
double[] z = new double[20];
int kph = 1;
int kguess = 0;
double D = 0;
int ierr = 0;
string herr = "".PadLeft(255);
TPRHOdll(ref T, ref P, z[0], ref kph, ref kguess, ref D, ref ierr, herr);
Console.WriteLine("TPRHOdll errorFlag " + ierr.ToString());
Console.WriteLine("Density calc: " + D.ToString());

Console.ReadLine();
```

If I run this with the DLL built by NIST (date on it is 5/21/2018), everything works as I expect: 
![image](https://user-images.githubusercontent.com/111408926/187263063-96ec82d4-88cf-4513-92e0-36c656752a9e.png)

If I run it with my DLL and no changes I get this error:
![image](https://user-images.githubusercontent.com/111408926/187263749-6128e71b-3b39-40c6-9f6e-e49126a19135.png)

Looking around at other issues, I thought the lengths of the strings might be an issue, but when I pad them (using PadLeft(255) and PadLeft(10000) on SETPATH and SETFLUIDS respectively) I still get this error:
![image](https://user-images.githubusercontent.com/111408926/187263849-5be56d72-f442-4f7f-b141-1c533bdbc791.png)

For some additional context (if it matters) - my end goal here is to use the Manager to allow running models that utilize REFPROP in parallel threads.

My current thought is that maybe I am using dated versions of the FORTRAN files.

Thanks for any advice.

**Comment by ianhbell** [comment]
Hmm, what about if you compile yourself with the REFPROP 10.0 sources? I vaguely recall there was an issue with some version(s) of Intel Fortran.  I will have to go back through the issues, or maybe you can do some googling in our issues.

Not the problem, but should fix: the argument to ``SETPATHdll`` is the folder that contains ``FLUIDS`` and ``MIXTURES`` folders

**Comment by ianhbell** [comment]
Also, I can email you the link to the beta FOTRAN files if you email me at ian.bell@nist.gov

**Comment by ScottALang** [comment]
Thank you for the very quick reply! I have sent you an email regarding the files.

I am not sure what you mean when you say "compile ... with the REFPROP 10.0 sources" - I thought I was using a version of 10.0 (it is possible something got mislabeled on our end).

**Comment by ianhbell** [comment]
The REFPROP 10.0 installation comes with the FORTRAN sources we used to build the DLL and that you could also use to build your own version with your compiler, we used an older compiler when compiling.

**Comment by kylemacfarlan** [comment]
I'm having the same issue. I am using the REFPROP 10.0 sources and building with Intel 2022.0.3. It seems to happen when trying to read the first fluid file. Was a real solution for this problem ever discovered? 

Note that I tried compiling on linux as well, using Ubuntu 22.04 and gfortran 11.3 and got a similar issue (segfault) at the same general point.

**Comment by ianhbell** [comment]
You need updated sources. Please email me (ian.bell@nist.gov) for a working set
