### ISSUE TITLE
Build issue on windows subsystem for linux (wsl)

### ISSUE THREAD

**Issue by thejashc** [usnistgov/REFPROP-cmake#80]
Hello, 

I am building REFPROP v9.1 on Windows10 in the wsl environment. 
I have installed the necessary prerequisites like python (v3.8, and numpy v1.24.3), gfortran (v 9.4.0) and cmake. 

The following error is encountered when I ran
```
> cmake --build .
Scanning dependencies of target REFPROP_H
[  3%] About to build the REFPROP.h header file w/ /usr/bin/python3.8;-u;/home/thejashc/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;/home/thejashc/REFPROP/fortran;--python-exe;/usr/bin/python3.8
Writing the .pyf file with numpy.f2py, please be patient...
About to run: /usr/bin/python3.8 -m numpy.f2py --quiet --no-lower -h REFPROP.pyf /home/thejashc/REFPROP/fortran/PASS_FTN.FOR
numpy version: 1.24.3
Deleting REFPROP.pyf
[  3%] Built target REFPROP_H
Scanning dependencies of target refprop
[  6%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/CMNS.FOR.o
[ 10%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/CORE_ANC.FOR.o
[ 13%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/CORE_BWR.FOR.o
[ 16%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/CORE_CPP.FOR.o
[ 20%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/CORE_DE.FOR.o
[ 23%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/CORE_ECS.FOR.o
[ 26%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/CORE_FEQ.FOR.o
[ 30%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/CORE_MLT.FOR.o
[ 33%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/CORE_PH0.FOR.o
[ 36%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/CORE_PR.FOR.o
[ 40%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/CORE_QUI.FOR.o
[ 43%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/CORE_STN.FOR.o
[ 46%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/FLASH2.FOR.o
[ 50%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/FLSH_SUB.FOR.o
[ 53%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/IDEALGAS.FOR.o
[ 56%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/MIX_AGA8.FOR.o
[ 60%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/MIX_HMX.FOR.o
[ 63%] Building Fortran object CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/PASS_FTN.FOR.o
/home/thejashc/REFPROP/fortran/PASS_FTN.FOR:4:6:

    4 |       dll_export RPVersion
      |      1
Error: Unclassifiable statement at (1)
make[2]: *** [CMakeFiles/refprop.dir/build.make:284: CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/PASS_FTN.FOR.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/refprop.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

I do not understand why the error `dll_export RPVersion` pops up,  
especially if it is inside a fortran code. 

Is there a way to overcome this ?

**Comment by ianhbell** [comment]
Can you please show the complete build log, not just the last part of it?

**Comment by thejashc** [comment]
Hello Ian, 

thanks for your response. 

Apologies. Please find the log attached with this message

[CMakeOutput.log](https://github.com/usnistgov/REFPROP-cmake/files/11382104/CMakeOutput.log)
.

**Comment by ianhbell** [comment]
Sorry, not that, but the shell output from running your cmake commands

**Comment by thejashc** [comment]
Apologies once again. 

I ran the following commands : 

[1] `cmake .. -DREFPROP_FORTRAN_PATH=../../REFPROP/fortran > log1.txt` 
[2] `cmake --build . > log2.txt` 

The shell outputs are collected in log1.txt and log2.txt, and I have attached them here. 

[log1.txt](https://github.com/usnistgov/REFPROP-cmake/files/11382405/log1.txt)
[log2.txt](https://github.com/usnistgov/REFPROP-cmake/files/11382409/log2.txt)

The error message that was not collected in log2.txt is pasted below : 

> /home/thejashc/REFPROP/fortran/PASS_FTN.FOR:4:6:

    4 |       dll_export RPVersion
      |      1
Error: Unclassifiable statement at (1)
make[2]: *** [CMakeFiles/refprop.dir/build.make:284: CMakeFiles/refprop.dir/home/thejashc/REFPROP/fortran/PASS_FTN.FOR.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/refprop.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by ianhbell** [comment]
That's a pretty ancient version of gfortran, how did you install it? On my mac, I'm at:
```
(py310) XXXX:teqp ihb$ gfortran --version
GNU Fortran (Homebrew GCC 12.2.0) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by ianhbell** [comment]
what os is being used in your WSL? I'd shoot for ubuntu 22.04

**Comment by thejashc** [comment]
I have ubuntu 20.04

**Comment by ianhbell** [comment]
I have built on 20.04 without problems: https://github.com/usnistgov/REFPROP-tests

**Comment by thejashc** [comment]
Perfect. Then I will update my Fortran compiler and see if this solves the issue.
