### ISSUE TITLE
ctREFPROP cannot find libgfortran.so.4

### ISSUE THREAD

**Issue by grgrynlds** [usnistgov/REFPROP-cmake#83]
I'm running REFPROP v10 on Ubuntu 22.04 and ctREFPROP is looking for libgfortran.so.4.  REFPROP v10 was working on Ubuntu 18 but now libgfortran.so.4 is not in anaconda3/lib, but only libgfortran.so.5.  Do I need to rebuild REFPROP to use libgfortran.so.5 or is there an easier way?

Thanks much,
Greg

**Comment by ianhbell** [comment]
Probably a rebuild is needed. I tried to statically link the gfortran, and that used to work, but that seems to have broken somewhere along the way.

**Comment by grgrynlds** [comment]
So I can save the FORTRAN & MIXTURE folders and just to cmake again?

**Comment by ianhbell** [comment]
Yup

**Comment by grgrynlds** [comment]
Thank you sir!!  I'll try that and let you know.
Greg

**Comment by grgrynlds** [comment]
Hi Ian, just a quick question.  I presently have...
 - FORTRAN, FLUIDS, MIXTURES in /home/greg/REFPROP
 - the new cloned REFPROP-cmake was built under /home/greg/anaconda3/lib/python3.9/site-packages/ctREFPROP/REFPROP-cmake.  In the previous install REFPROP-cmake was at /home/greg/REFPROP-cmake but I'm presently using and maintaining python via anaconda which seems to be good.
 - so my question is, should I do the build with REFPROP-cmake as located under anaconda3, or should I move REFPROP-cmake to /home/greg and do the build there?  The /home/greg/REFPROP seems to be a good location for the resulting .so but I have no preference on the REFPROP-cmake folder.

Thanks,
Greg

**Comment by ianhbell** [comment]
You're welcome, just doing my job :)

**Comment by grgrynlds** [comment]
Well, I really appreciate your prompt replies... so I can do my job :)
Greg
