### ISSUE TITLE
arm64 compile _seems_ to have worked with Macports GCC-12

### ISSUE THREAD

**Issue by jonCAstickel** [usnistgov/REFPROP-cmake#85]
This is more of a comment than an issue. I use Macports rather than Homebrew on my Mac with an M2 cpu. Macports installed GCC (gcc-12) does not have the capability to compile `x86-64`, only `arm64`. So I tried it, and it seems to have worked! I used:
```
port select gcc mp-gcc12
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
```
Then in iPython:
```
In [1]: from CoolProp import CoolProp

In [2]: CoolProp.PropsSI("T","P",101325,"Q",0,"REFPROP::Water")
Out[2]: 373.1242958476957
```
I could make a PR to update the Mac section of the README if you like.

**Comment by ianhbell** [comment]
I'm not sure that really requires an update to docs, but you can open and PR and I can review it if you like
