### ISSUE TITLE
Suggested Version of Numpy

### ISSUE THREAD

**Issue by MitchelDaniel** [usnistgov/REFPROP-cmake#88]
Hi Ian,

What version of numpy have you gotten to work in a linux enviroment?
when I try to build with 1.24.4 or 1.14.6, I get 
```
...
ModuleNotFoundError: No module named 'numpy'
make[2]: *** [CMakeFiles/REFPROP_H.dir/build.make:61: REFPROP.h.stamp] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/REFPROP_H.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
`ls /usr/bin/python` shows these versions of python:
I have python2, python2.7, python3, python3.8

**Comment by ianhbell** [comment]
All of the numpy are usually fine. Make sure you are installing into the python you think you are, something like: ``python -m pip install numpy``
