### ISSUE TITLE
CSTAR Speed Improvements??

### ISSUE THREAD

**Issue by MitchelDaniel** [usnistgov/REFPROP-cmake#89]
Hello,

I've noticed that when calling CStar (or CCRIT), it takes about 100x longer than any of the other subroutines I'm calling. I understand that this is an iterative function, so of course it will take longer, but do you have any recommendations on how to speed this up? Possibly an alternate function that gets the same job done, maybe a way to lower the number of iterations?

It takes almost 2 seconds to complete a calculation for a mixture.

Mind you I am using librefprop.so with REFPROP <= 9.1, my company is in the process of getting 10, and then I will attempt to build the new library using cmake.

Working on a linux machine

Thanks

**Comment by ianhbell** [comment]
What about doing the iteration yourself? That might be somewhat faster.

**Comment by MitchelDaniel** [comment]
Do you mean looking in the fortran functions and writing it in my function I was calling CSTAR from?

**Comment by ianhbell** [comment]
Yup

**Comment by MitchelDaniel** [comment]
I can try that. I'll translate the Fortran code of CSTAR in Flash2 into my C function. Why do you think that could speed it up?

Related question: have you heard reports of the Refprop.DLL bring faster than its Linux library counterpart?

**Comment by ianhbell** [comment]
I'm not really sure, but perhaps you could use a more speedy algorithm. But you will have to pay for the convenience of calls going across the Python-> fortran-> Python interface

**Comment by ianhbell** [comment]
Regarding the related question, that could have to do with how it is compiled. You want to compile with Intel Fortran, as that makes a non-trivial difference. That's what is used on windows.
