### ISSUE TITLE
CMake using VS 2019 does not find Fortran compiler.

### ISSUE THREAD

**Issue by marc53042** [usnistgov/REFPROP-cmake#95]
Hi Ian, 

I cloned the REFPROP-cmake package into my desktop computer and tried to generate a REFPROP.DLL using Visual Studio 2019 but it has not worked so far. I got the following error message:  
Severity	Code	Description	Project	File	Line	Suppression State

Error		CMake Error at C:\Users\REFPROP-cmake\CMakeLists.txt:3 (enable_language):
  The CMAKE_Fortran_COMPILER:

    /bin /intel64 /ifort.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH

I localized the corresponding location of the ifort.exe file and set in the CMakeCache.txt file in two separate lines:
1) //Path to a program.
CMAKE_DLLTOOL:FILEPATH=C:/Program Files (x86)/Intel/oneAPI/compiler/2022.0.0/windows/

2)  //Fortran compiler
CMAKE_Fortran_COMPILER:STRING=/bin /intel64 /ifort.exe

As you can see above in 2) the Fortran compiler line only accepts string value, hence I provided the corresponding location using backslash. Only 1) accepts filepath information, where I set the location of the compiler.
In any case, it did not work.

Any help or suggestion will be greatly appreciated.
Thanks,

**Comment by ianhbell** [comment]
Usually it "just works" for me if Visual Studio and Intel are installed in the proper manner. If not, you may need to specify the absolute path to the ``ifort`` executable via the ``-DCMAKE_Fortran_COMPILER=/abs/path/to/ifort.exe`` argument when you do the config step with cmake.  Please show what commands you ran at the command line.

**Comment by marc53042** [comment]
1> Command line: "C:\WINDOWS\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\lparedes\source\repos\REFPROP-cmake\out\install\x64-Debug" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\lparedes\source\repos\REFPROP-cmake" 2>&1"

**Comment by ianhbell** [comment]
Huh? The command should look something like:

```
cmake .. -DCMAKE_Fortran_COMPILER=/path/to/intel/ifort.exe -DREFPROP_FORTRAN_PATH=/path/to/FORTRAN
```
in the build folder

**Comment by marc53042** [comment]
This is what I get as soon as I launch it. Any idea of what I am missing here?

**Comment by ianhbell** [comment]
Can you go even simpler? Open a terminal in the sources folder (the one containing CMakeLists.txt), then:
```
mkdir bld
cd bld
cmake .. -DREFPROP_FORTRAN_PATH=/path/to/FORTRAN
```
where ``/path/to/FORTRAN`` is the path to the FORTRAN folder of your REFPROP installation?

**Comment by marc53042** [comment]
It is even worse because cmd does not even recognize the other compilers (C and CXX) which were by VS2019.


C:\Users\lparedes\source\repos\REFPROP-cmake\bld>cmake .. -DREFPROP_FORTRAN_PATH=C:\Users\lparedes\source\repos\REFPROP-cmake\FORTRAN
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!

**Comment by ianhbell** [comment]
Can you try from a Visual Studio shell?

**Comment by marc53042** [comment]
This time C and CXX were found, but Fortran continues missing:

PS C:\Users\lparedes\Source\Repos\REFPROP-cmake> cd bld
PS C:\Users\lparedes\Source\Repos\REFPROP-cmake\bld> cmake .. -DREFPROP_FORTRAN_PATH=C:\Users\lparedes\source\repos\REFPROP-cmake
-- Building for: Ninja
-- The C compiler identification is MSVC 19.29.30154.0
-- The CXX compiler identification is MSVC 19.29.30154.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx86/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The Fortran compiler identification is unknown
CMake Error at CMakeLists.txt:3 (enable_language):
  No CMAKE_Fortran_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!

**Comment by ianhbell** [comment]
Progress - what if you pass the path as we discussed before?

**Comment by marc53042** [comment]
Thanks, Ian for still being there. I made some progress as I got a different error message this time...rsrsrs
I typed in the VS shell the following command line: 

cmake .. -DCMAKE_Fortran_COMPILER=C:"/Program Files (x86)/Intel/oneAPI/compiler/2022.0.0/windows/bin/intel64/ifort.exe" -DREFPROP_FORTRAN_PATH=C:"/Program Files (x86)/REFPROP/FORTRAN"

and the system outputs the following:
-- The Fortran compiler identification is unknown
Intel(R) Fortran Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.5.0 Build 20211109_000000
Copyright (C) 1985-2021 Intel Corporation.  All rights reserved.

-- Detecting Fortran compiler ABI info
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_Fortran_PREPROCESS_SOURCE
CMake Error at C:/msys64/mingw64/share/cmake/Modules/CMakeDetermineCompilerABI.cmake:64 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  C:/msys64/mingw64/share/cmake/Modules/CMakeTestFortranCompiler.cmake:20 (CMAKE_DETERMINE_COMPILER_ABI)
  CMakeLists.txt:3 (enable_language)


-- Configuring incomplete, errors occurred!

**Comment by marc53042** [comment]
It seems the system finally recognized fortran location, but fails to build

**Comment by ianhbell** [comment]
Some things I note:
1) You should have a normal cmake installation, not coming from msys or mingw; that is always going to cause problems if you use msys or mingw
2) Are you sure that your intel fortran is installed properly? It should be installed AFTER the visual studio, so that the integration with VS works properly

**Comment by ianhbell** [comment]
Why is ninja the generator? Did you select it yourself? You probably want Visual Studio as generator to have the right link with Intel Fortran.

**Comment by marc53042** [comment]
Yes, I can assure you that because otherwise Abaqus-fortran connection for user-defined subroutines would not work. 
I always verify this by running Abaqus verification.

**Comment by ianhbell** [comment]
Ok, when we have to force the Visual Studio generator, otherwise this will not work (without additional hoops) I think.

**Comment by marc53042** [comment]
> Why is ninja the generator? Did you select it yourself? You probably want Visual Studio as generator to have the right link with Intel Fortran.

That option is default by the system. I do not have a specific preference on this.

**Comment by ianhbell** [comment]
Ninja doesn't know anything about Intel Fortran which is why this doesn't work.

**Comment by marc53042** [comment]
Ok. I will try to change that. Could you suggest how?

**Comment by marc53042** [comment]
I found this in json file: 
{
  "configurations": [
    {
      "name": "x64-Debug",
      "generator": "Ninja",
      "configurationType": "Release",
      "inheritEnvironments": [ "msvc_x64_x64" ],
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "",
      "ctestCommandArgs": ""
    }
  ]
}

**Comment by ianhbell** [comment]
Check out ``cmake --help``. Basically something like ``cmake -G "Visual Studio 19 2022" -A x64`` or something like that. I can never remember the precise argument

**Comment by marc53042** [comment]
I believe I can change the generator by other one, right?

**Comment by ianhbell** [comment]
And make sure you delete your build folder before you change the generator

**Comment by marc53042** [comment]
Ok. It seems that finally ran until the end without crashing after I set it for Visual Studio 16 2019.!!
But it still is not able to generate the dll file:

>------ Build All started: Project: REFPROP-cmake, Configuration: x64-Debug ------
  
  Microsoft Visual Studio 2019 Version 16.11.34.
  Copyright (C) Microsoft Corp. All rights reserved.
  
  Package 'IFLangServicePackage' failed to load.
  
  Package 'IFLangServicePackage' failed to load.
  Build started...
  1>------ Build started: Project: ZERO_CHECK, Configuration: Release Win32 ------
  1>Checking Build System
  2>------ Build started: Project: REFPROP_H, Configuration: Release Win32 ------
  3>------ Build started: Project: REFPROP, Configuration: Release Win32 ------
  3>Compiling with Intel® Fortran Compiler Classic 2021.5.0 [IA-32]...
  3>REFPROP.FOR
  2>About to build the REFPROP.h header file w/ C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python39_64/python.exe;-u;C:/Users/lparedes/source/Repos/REFPROP-cmake/externals/REFPROP-headers/generate_header.py;--FORTRAN-path;C:/Users/lparedes/source/Repos/REFPROP-cmake/FORTRAN/DLLFILES;--python-exe;C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python39_64/python.exe
  2>Traceback (most recent call last):
  2>  File "C:\Users\lparedes\source\Repos\REFPROP-cmake\externals\REFPROP-headers\generate_header.py", line 2, in <module>
  2>    import subprocess, sys, six, os, re
  2>ModuleNotFoundError: No module named 'six'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for 'C:\Users\lparedes\source\Repos\REFPROP-cmake\out\build\x64-Debug\CMakeFiles\9267b49ac87e5a0670f0afc57bf68f1f\REFPROP.h.stamp.rule;C:\Users\lparedes\source\Repos\REFPROP-cmake\out\build\x64-Debug\CMakeFiles\a32b506fb15fade678aa96dd24acc73c\REFPROP_H.rule' exited with code 1.
  2>Done building project "REFPROP_H.vcxproj" -- FAILED.
  3>SAT_SUB.FOR
  3>TRNS_TCX.FOR
  3>CORE_PR.FOR
  3>SETUP.FOR
  3>CORE_ANC.FOR
  3>UTILITY.FOR
  3>TRNS_VIS.FOR
  3>TRNSP.FOR
  3>PASS_FTN.FOR
  3>MIX_HMX.FOR
  3>PROP_SUB.FOR
  3>FLSH_SUB.FOR
  3>CORE_FEQ.FOR
  3>Linking...
  3>Microsoft (R) Incremental Linker Version 14.29.30154.0
  3>Copyright (C) Microsoft Corporation.  All rights reserved.
  3>/OUT:C:\Users\lparedes\source\Repos\REFPROP-cmake\out\build\x64-Debug\Release\REFPROP.dll
  3>/VERSION:0.0
  3>/INCREMENTAL:NO
  3>/MANIFEST
  3>/MANIFESTFILE:REFPROP.dir\Release\REFPROP.dll.intermediate.manifest
  3>"/MANIFESTUAC:level='asInvoker' uiAccess='false'"
  3>/IMPLIB:C:\Users\lparedes\source\Repos\REFPROP-cmake\out\build\x64-Debug\Release\REFPROP.lib
  3>/DLL
  3>user32.lib
  3>/machine:X86
  3>REFPROP.dir\Release\REFPROP.obj
  3>REFPROP.dir\Release\SAT_SUB.obj
  3>REFPROP.dir\Release\TRNS_TCX.obj
  3>REFPROP.dir\Release\CORE_PR.obj
  3>REFPROP.dir\Release\SETUP.obj
  3>REFPROP.dir\Release\CORE_ANC.obj
  3>REFPROP.dir\Release\UTILITY.obj
  3>REFPROP.dir\Release\TRNS_VIS.obj
  3>REFPROP.dir\Release\TRNSP.obj
  3>REFPROP.dir\Release\PASS_FTN.obj
  3>REFPROP.dir\Release\MIX_HMX.obj
  3>REFPROP.dir\Release\PROP_SUB.obj
  3>REFPROP.dir\Release\FLSH_SUB.obj
  3>REFPROP.dir\Release\CORE_FEQ.obj
  3>   Creating library C:\Users\lparedes\source\Repos\REFPROP-cmake\out\build\x64-Debug\Release\REFPROP.lib and object C:\Users\lparedes\source\Repos\REFPROP-cmake\out\build\x64-Debug\Release\REFPROP.exp
  3>Embedding manifest...
  3>Microsoft (R) Manifest Tool
  3>Copyright (c) Microsoft Corporation.
  3>All rights reserved.
  3>
  3>Build log written to  "file://C:\Users\lparedes\source\Repos\REFPROP-cmake\out\build\x64-Debug\REFPROP.dir\Release\BuildLog.htm"
  3>REFPROP - 0 error(s), 0 warning(s)
  4>------ Build started: Project: ALL_BUILD, Configuration: Release Win32 ------
  4>Building Custom Rule C:/Users/lparedes/source/Repos/REFPROP-cmake/CMakeLists.txt
  ========== Build: 3 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Build All failed.

**Comment by ianhbell** [comment]
You need to install the six package in your python; see the error message; it was mentioned in the docs. I guess I could drop that dependency since python 2.7 is finally really dead.  You are basically there now.

**Comment by ianhbell** [comment]
You want the six package, and once you do that you will have a fully functional install. You can probably disable the python stuff because it is mostly used to get other compilers to behave like Intel. Please read the docs.
