### ISSUE TITLE
MatLab compatibility

### ISSUE THREAD

**Issue by devoniodd** [usnistgov/REFPROP-cmake#97]
Hello, I am not sure if this is the right repo for the issue, if not I'll be happy to change it up.
I have managed to build Refprop on my M1 Pro MacBook by following the instruction on the repo. I am now though stuck trying to get it working with Matlab. From what I can see the function refprop.m provided at https://trc.nist.gov/refprop/LINKING/Linking.htm does not even contain the word ".dylib", which, from what little I understand, is the MacOS equivalent of dll. 
How can I solve this? Thanks in advance

**Comment by ianhbell** [comment]
Please see: https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/MATLAB . That is the only supported interface for MATLAB.
